// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#include "config.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_2eproto = nullptr;
const ::uint32_t TableStruct_config_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_config_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014config.proto\022\022Nrmk.IndyFramework\032\021conf"
    "ig_msgs.proto\032\021common_msgs.proto2\205<\n\006Con"
    "fig\022B\n\010GetNonce\022\031.Nrmk.IndyFramework.Emp"
    "ty\032\031.Nrmk.IndyFramework.Nonce\"\000\022C\n\005Login"
    "\022\032.Nrmk.IndyFramework.Digest\032\034.Nrmk.Indy"
    "Framework.LoginRes\"\000\022F\n\nTestDigest\022\032.Nrm"
    "k.IndyFramework.Passwd\032\032.Nrmk.IndyFramew"
    "ork.Digest\"\000\022H\n\013VerifyToken\022\031.Nrmk.IndyF"
    "ramework.Token\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022W\n\016ChangePassword\022%.Nrmk.IndyFram"
    "ework.ChangePasswordReq\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022L\n\rGetPathConfig\022\031.Nrmk."
    "IndyFramework.Empty\032\036.Nrmk.IndyFramework"
    ".PathConfig\"\000\022E\n\013GetRefFrame\022\031.Nrmk.Indy"
    "Framework.Empty\032\031.Nrmk.IndyFramework.Fra"
    "me\"\000\022H\n\013SetRefFrame\022\031.Nrmk.IndyFramework"
    ".Frame\032\034.Nrmk.IndyFramework.Response\"\000\022W"
    "\n\021SetRefFramePlanar\022\037.Nrmk.IndyFramework"
    ".PlanarFrame\032\037.Nrmk.IndyFramework.FrameR"
    "esult\"\000\022I\n\016SetLockedJoint\022\027.Nrmk.IndyFra"
    "mework.Int\032\034.Nrmk.IndyFramework.Response"
    "\"\000\022F\n\013SetToolLink\022\027.Nrmk.IndyFramework.I"
    "nt\032\034.Nrmk.IndyFramework.Response\"\000\022I\n\014Se"
    "tToolFrame\022\031.Nrmk.IndyFramework.Frame\032\034."
    "Nrmk.IndyFramework.Response\"\000\022J\n\rSetSpee"
    "dRatio\022\031.Nrmk.IndyFramework.Ratio\032\034.Nrmk"
    ".IndyFramework.Response\"\000\022G\n\rGetSpeedRat"
    "io\022\031.Nrmk.IndyFramework.Empty\032\031.Nrmk.Ind"
    "yFramework.Ratio\"\000\022S\n\017SetDIConfigList\022 ."
    "Nrmk.IndyFramework.DIConfigList\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022P\n\017GetDIConfigLi"
    "st\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.Ind"
    "yFramework.DIConfigList\"\000\022S\n\017SetDOConfig"
    "List\022 .Nrmk.IndyFramework.DOConfigList\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022P\n\017GetDOC"
    "onfigList\022\031.Nrmk.IndyFramework.Empty\032 .N"
    "rmk.IndyFramework.DOConfigList\"\000\022O\n\017SetH"
    "omePosition\022\034.Nrmk.IndyFramework.JointPo"
    "s\032\034.Nrmk.IndyFramework.Response\"\000\022L\n\017Get"
    "HomePosition\022\031.Nrmk.IndyFramework.Empty\032"
    "\034.Nrmk.IndyFramework.JointPos\"\000\022L\n\017GetPa"
    "ckPosition\022\031.Nrmk.IndyFramework.Empty\032\034."
    "Nrmk.IndyFramework.JointPos\"\000\022K\n\013SetTool"
    "List\022\034.Nrmk.IndyFramework.ToolList\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022H\n\013GetToolLis"
    "t\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.Indy"
    "Framework.ToolList\"\000\022X\n\023GetVisionServerL"
    "ist\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.In"
    "dyFramework.VisionServerList\"\000\022[\n\023SetVis"
    "ionServerList\022$.Nrmk.IndyFramework.Visio"
    "nServerList\032\034.Nrmk.IndyFramework.Respons"
    "e\"\000\022X\n\023GetModbusServerList\022\031.Nrmk.IndyFr"
    "amework.Empty\032$.Nrmk.IndyFramework.Modbu"
    "sServerList\"\000\022[\n\023SetModbusServerList\022$.N"
    "rmk.IndyFramework.ModbusServerList\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022P\n\017GetConveyo"
    "rList\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk."
    "IndyFramework.ConveyorList\"\000\022S\n\017SetConve"
    "yorList\022 .Nrmk.IndyFramework.ConveyorLis"
    "t\032\034.Nrmk.IndyFramework.Response\"\000\022Y\n\017Set"
    "AutoServoOff\022&.Nrmk.IndyFramework.AutoSe"
    "rvoOffConfig\032\034.Nrmk.IndyFramework.Respon"
    "se\"\000\022V\n\017GetAutoServoOff\022\031.Nrmk.IndyFrame"
    "work.Empty\032&.Nrmk.IndyFramework.AutoServ"
    "oOffConfig\"\000\022W\n\023SetJointControlGain\022 .Nr"
    "mk.IndyFramework.JointGainSet\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022T\n\023GetJointControl"
    "Gain\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.I"
    "ndyFramework.JointGainSet\"\000\022U\n\022SetTaskCo"
    "ntrolGain\022\037.Nrmk.IndyFramework.TaskGainS"
    "et\032\034.Nrmk.IndyFramework.Response\"\000\022R\n\022Ge"
    "tTaskControlGain\022\031.Nrmk.IndyFramework.Em"
    "pty\032\037.Nrmk.IndyFramework.TaskGainSet\"\000\022_"
    "\n\027SetImpedanceControlGain\022$.Nrmk.IndyFra"
    "mework.ImpedanceGainSet\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022\\\n\027GetImpedanceControlGa"
    "in\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.Ind"
    "yFramework.ImpedanceGainSet\"\000\022W\n\023SetForc"
    "eControlGain\022 .Nrmk.IndyFramework.ForceG"
    "ainSet\032\034.Nrmk.IndyFramework.Response\"\000\022T"
    "\n\023GetForceControlGain\022\031.Nrmk.IndyFramewo"
    "rk.Empty\032 .Nrmk.IndyFramework.ForceGainS"
    "et\"\000\022U\n\022SetTestControlGain\022\037.Nrmk.IndyFr"
    "amework.TestGainSet\032\034.Nrmk.IndyFramework"
    ".Response\"\000\022R\n\022GetTestControlGain\022\031.Nrmk"
    ".IndyFramework.Empty\032\037.Nrmk.IndyFramewor"
    "k.TestGainSet\"\000\022Y\n\024SetCustomControlGain\022"
    "!.Nrmk.IndyFramework.CustomGainSet\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022V\n\024GetCustomC"
    "ontrolGain\022\031.Nrmk.IndyFramework.Empty\032!."
    "Nrmk.IndyFramework.CustomGainSet\"\000\022g\n\031Se"
    "tNewControllerTestOnOff\022*.Nrmk.IndyFrame"
    "work.NewControllerTestState\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022i\n\036GetNewControllerT"
    "estOnOffState\022\031.Nrmk.IndyFramework.Empty"
    "\032*.Nrmk.IndyFramework.NewControllerTestS"
    "tate\"\000\022f\n\035SetComplianceControlJointGain\022"
    "%.Nrmk.IndyFramework.ComplianceGainSet\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022c\n\035GetCom"
    "plianceControlJointGain\022\031.Nrmk.IndyFrame"
    "work.Empty\032%.Nrmk.IndyFramework.Complian"
    "ceGainSet\"\000\022V\n\017SetFrictionComp\022#.Nrmk.In"
    "dyFramework.FrictionCompSet\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022S\n\017GetFrictionComp\022\031"
    ".Nrmk.IndyFramework.Empty\032#.Nrmk.IndyFra"
    "mework.FrictionCompSet\"\000\022Q\n\013SetMountPos\022"
    "\".Nrmk.IndyFramework.MountingAngles\032\034.Nr"
    "mk.IndyFramework.Response\"\000\022N\n\013GetMountP"
    "os\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk.Ind"
    "yFramework.MountingAngles\"\000\022U\n\017SetToolPr"
    "operty\022\".Nrmk.IndyFramework.ToolProperti"
    "es\032\034.Nrmk.IndyFramework.Response\"\000\022R\n\017Ge"
    "tToolProperty\022\031.Nrmk.IndyFramework.Empty"
    "\032\".Nrmk.IndyFramework.ToolProperties\"\000\022R"
    "\n\020GetToolFrameList\022\031.Nrmk.IndyFramework."
    "Empty\032!.Nrmk.IndyFramework.ToolFrameList"
    "\"\000\022U\n\020SetToolFrameList\022!.Nrmk.IndyFramew"
    "ork.ToolFrameList\032\034.Nrmk.IndyFramework.R"
    "esponse\"\000\022P\n\017GetRefFrameList\022\031.Nrmk.Indy"
    "Framework.Empty\032 .Nrmk.IndyFramework.Ref"
    "FrameList\"\000\022S\n\017SetRefFrameList\022 .Nrmk.In"
    "dyFramework.RefFrameList\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022R\n\020GetCustomPosList\022\031.N"
    "rmk.IndyFramework.Empty\032!.Nrmk.IndyFrame"
    "work.CustomPosList\"\000\022U\n\020SetCustomPosList"
    "\022!.Nrmk.IndyFramework.CustomPosList\032\034.Nr"
    "mk.IndyFramework.Response\"\000\022Z\n\020SetCollSe"
    "nsLevel\022&.Nrmk.IndyFramework.CollisionSe"
    "nsLevel\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "W\n\020GetCollSensLevel\022\031.Nrmk.IndyFramework"
    ".Empty\032&.Nrmk.IndyFramework.CollisionSen"
    "sLevel\"\000\022[\n\020SetCollSensParam\022\'.Nrmk.Indy"
    "Framework.CollisionThresholds\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022X\n\020GetCollSensPara"
    "m\022\031.Nrmk.IndyFramework.Empty\032\'.Nrmk.Indy"
    "Framework.CollisionThresholds\"\000\022_\n\027GetDe"
    "faultCollSensParam\022\031.Nrmk.IndyFramework."
    "Empty\032\'.Nrmk.IndyFramework.CollisionThre"
    "sholds\"\000\022T\n\rSetCollPolicy\022#.Nrmk.IndyFra"
    "mework.CollisionPolicy\032\034.Nrmk.IndyFramew"
    "ork.Response\"\000\022Q\n\rGetCollPolicy\022\031.Nrmk.I"
    "ndyFramework.Empty\032#.Nrmk.IndyFramework."
    "CollisionPolicy\"\000\022c\n\027SetOnStartProgramCo"
    "nfig\022(.Nrmk.IndyFramework.OnStartProgram"
    "Config\032\034.Nrmk.IndyFramework.Response\"\000\022`"
    "\n\027GetOnStartProgramConfig\022\031.Nrmk.IndyFra"
    "mework.Empty\032(.Nrmk.IndyFramework.OnStar"
    "tProgramConfig\"\000\022S\n\026SetSimpleCollThresho"
    "ld\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022S\n\017SetSafetyLimits"
    "\022 .Nrmk.IndyFramework.SafetyLimits\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022P\n\017GetSafetyL"
    "imits\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk."
    "IndyFramework.SafetyLimits\"\000\022[\n\023SetSafet"
    "yStopConfig\022$.Nrmk.IndyFramework.SafetyS"
    "topConfig\032\034.Nrmk.IndyFramework.Response\""
    "\000\022X\n\023GetSafetyStopConfig\022\031.Nrmk.IndyFram"
    "ework.Empty\032$.Nrmk.IndyFramework.SafetyS"
    "topConfig\"\000\022V\n\017GetReducedRatio\022\031.Nrmk.In"
    "dyFramework.Empty\032&.Nrmk.IndyFramework.G"
    "etReducedRatioRes\"\000\022V\n\017GetReducedSpeed\022\031"
    ".Nrmk.IndyFramework.Empty\032&.Nrmk.IndyFra"
    "mework.GetReducedSpeedRes\"\000\022Y\n\017SetReduce"
    "dSpeed\022&.Nrmk.IndyFramework.SetReducedSp"
    "eedReq\032\034.Nrmk.IndyFramework.Response\"\000\022W"
    "\n\021SetFTSensorConfig\022\".Nrmk.IndyFramework"
    ".FTSensorDevice\032\034.Nrmk.IndyFramework.Res"
    "ponse\"\000\022T\n\021GetFTSensorConfig\022\031.Nrmk.Indy"
    "Framework.Empty\032\".Nrmk.IndyFramework.FTS"
    "ensorDevice\"\000\022S\n\017SetTeleOpParams\022 .Nrmk."
    "IndyFramework.TeleOpParams\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022P\n\017GetTeleOpParams\022\031."
    "Nrmk.IndyFramework.Empty\032 .Nrmk.IndyFram"
    "ework.TeleOpParams\"\000\022X\n\023GetKinematicsPar"
    "ams\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.In"
    "dyFramework.KinematicsParams\"\000\022_\n\026GetCol"
    "lisonModelMargin\022\031.Nrmk.IndyFramework.Em"
    "pty\032(.Nrmk.IndyFramework.CollisionModelM"
    "argin\"\000\022b\n\026SetCollisonModelMargin\022(.Nrmk"
    ".IndyFramework.CollisionModelMargin\032\034.Nr"
    "mk.IndyFramework.Response\"\000\022U\n\020SetToolSh"
    "apeList\022!.Nrmk.IndyFramework.ToolShapeLi"
    "st\032\034.Nrmk.IndyFramework.Response\"\000\022R\n\020Ge"
    "tToolShapeList\022\031.Nrmk.IndyFramework.Empt"
    "y\032!.Nrmk.IndyFramework.ToolShapeList\"\000\022Y"
    "\n\022SetEnvironmentList\022#.Nrmk.IndyFramewor"
    "k.EnvironmentList\032\034.Nrmk.IndyFramework.R"
    "esponse\"\000\022V\n\022GetEnvironmentList\022\031.Nrmk.I"
    "ndyFramework.Empty\032#.Nrmk.IndyFramework."
    "EnvironmentList\"\000\022[\n\023SetSensorlessParams"
    "\022$.Nrmk.IndyFramework.SensorlessParams\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022X\n\023GetSen"
    "sorlessParams\022\031.Nrmk.IndyFramework.Empty"
    "\032$.Nrmk.IndyFramework.SensorlessParams\"\000"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_config_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_config_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_config_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false,
    false,
    7768,
    descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once,
    descriptor_table_config_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_config_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_config_2eproto_getter() {
  return &descriptor_table_config_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_config_2eproto(&descriptor_table_config_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
