// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#include "control.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_control_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_control_2eproto = nullptr;
const ::uint32_t TableStruct_control_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_control_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rcontrol.proto\022\022Nrmk.IndyFramework\032\022con"
    "trol_msgs.proto\032\021config_msgs.proto\032\021comm"
    "on_msgs.proto2\332A\n\007Control\022N\n\016GetControlI"
    "nfo\022\031.Nrmk.IndyFramework.Empty\032\037.Nrmk.In"
    "dyFramework.ControlInfo\"\000\022[\n\017ActivateInd"
    "ySDK\022\".Nrmk.IndyFramework.SDKLicenseInfo"
    "\032\".Nrmk.IndyFramework.SDKLicenseResp\"\000\022E"
    "\n\005MoveJ\022\034.Nrmk.IndyFramework.MoveJReq\032\034."
    "Nrmk.IndyFramework.Response\"\000\022G\n\006MoveJT\022"
    "\035.Nrmk.IndyFramework.MoveJTReq\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022E\n\005MoveL\022\034.Nrmk.I"
    "ndyFramework.MoveLReq\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022G\n\006MoveLT\022\035.Nrmk.IndyFrame"
    "work.MoveLTReq\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022E\n\005MoveC\022\034.Nrmk.IndyFramework.Mov"
    "eCReq\032\034.Nrmk.IndyFramework.Response\"\000\022G\n"
    "\006MoveCT\022\035.Nrmk.IndyFramework.MoveCTReq\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022U\n\rMoveJo"
    "intTraj\022$.Nrmk.IndyFramework.MoveJointTr"
    "ajReq\032\034.Nrmk.IndyFramework.Response\"\000\022S\n"
    "\014MoveTaskTraj\022#.Nrmk.IndyFramework.MoveT"
    "askTrajReq\032\034.Nrmk.IndyFramework.Response"
    "\"\000\022M\n\tMoveGcode\022 .Nrmk.IndyFramework.Mov"
    "eGcodeReq\032\034.Nrmk.IndyFramework.Response\""
    "\000\022S\n\014MoveConveyor\022#.Nrmk.IndyFramework.M"
    "oveConveyorReq\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022G\n\006WaitIO\022\035.Nrmk.IndyFramework.Wa"
    "itIOReq\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "K\n\010WaitTime\022\037.Nrmk.IndyFramework.WaitTim"
    "eReq\032\034.Nrmk.IndyFramework.Response\"\000\022S\n\014"
    "WaitProgress\022#.Nrmk.IndyFramework.WaitPr"
    "ogressReq\032\034.Nrmk.IndyFramework.Response\""
    "\000\022K\n\010WaitTraj\022\037.Nrmk.IndyFramework.WaitT"
    "rajReq\032\034.Nrmk.IndyFramework.Response\"\000\022O"
    "\n\nWaitRadius\022!.Nrmk.IndyFramework.WaitRa"
    "diusReq\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "M\n\tMoveJCond\022 .Nrmk.IndyFramework.MoveJC"
    "ondReq\032\034.Nrmk.IndyFramework.Response\"\000\022Q"
    "\n\016MoveLinearAxis\022\037.Nrmk.IndyFramework.Mo"
    "veAxisReq\032\034.Nrmk.IndyFramework.Response\""
    "\000\022I\n\nStopMotion\022\033.Nrmk.IndyFramework.Sto"
    "pCat\032\034.Nrmk.IndyFramework.Response\"\000\022K\n\013"
    "PauseMotion\022\034.Nrmk.IndyFramework.PauseCa"
    "t\032\034.Nrmk.IndyFramework.Response\"\000\022N\n\021Set"
    "DirectTeaching\022\031.Nrmk.IndyFramework.Stat"
    "e\032\034.Nrmk.IndyFramework.Response\"\000\022N\n\021Set"
    "SimulationMode\022\031.Nrmk.IndyFramework.Stat"
    "e\032\034.Nrmk.IndyFramework.Response\"\000\022S\n\024Set"
    "CustomControlMode\022\033.Nrmk.IndyFramework.I"
    "ntMode\032\034.Nrmk.IndyFramework.Response\"\000\022P"
    "\n\024GetCustomControlMode\022\031.Nrmk.IndyFramew"
    "ork.Empty\032\033.Nrmk.IndyFramework.IntMode\"\000"
    "\022T\n\027SetFrictionCompensation\022\031.Nrmk.IndyF"
    "ramework.State\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022V\n\034GetFrictionCompensationState\022\031"
    ".Nrmk.IndyFramework.Empty\032\031.Nrmk.IndyFra"
    "mework.State\"\000\022K\n\013SetTactTime\022\034.Nrmk.Ind"
    "yFramework.TactTime\032\034.Nrmk.IndyFramework"
    ".Response\"\000\022H\n\013GetTactTime\022\031.Nrmk.IndyFr"
    "amework.Empty\032\034.Nrmk.IndyFramework.TactT"
    "ime\"\000\022W\n\021SetComplianceMode\022\".Nrmk.IndyFr"
    "amework.ComplianceMode\032\034.Nrmk.IndyFramew"
    "ork.Response\"\000\022T\n\021GetComplianceMode\022\031.Nr"
    "mk.IndyFramework.Empty\032\".Nrmk.IndyFramew"
    "ork.ComplianceMode\"\000\022D\n\007Recover\022\031.Nrmk.I"
    "ndyFramework.Empty\032\034.Nrmk.IndyFramework."
    "Response\"\000\022C\n\006Reboot\022\031.Nrmk.IndyFramewor"
    "k.Empty\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "N\n\021SetManualRecovery\022\031.Nrmk.IndyFramewor"
    "k.State\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "O\n\020MoveRecoverJoint\022\033.Nrmk.IndyFramework"
    ".TargetJ\032\034.Nrmk.IndyFramework.Response\"\000"
    "\022O\n\rSearchProgram\022\033.Nrmk.IndyFramework.P"
    "rogram\032\037.Nrmk.IndyFramework.ProgramInfo\""
    "\000\022J\n\013PlayProgram\022\033.Nrmk.IndyFramework.Pr"
    "ogram\032\034.Nrmk.IndyFramework.Response\"\000\022I\n"
    "\014PauseProgram\022\031.Nrmk.IndyFramework.Empty"
    "\032\034.Nrmk.IndyFramework.Response\"\000\022J\n\rResu"
    "meProgram\022\031.Nrmk.IndyFramework.Empty\032\034.N"
    "rmk.IndyFramework.Response\"\000\022H\n\013StopProg"
    "ram\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022E\n\tSendAlarm\022\033.Nr"
    "mk.IndyFramework.Message\032\031.Nrmk.IndyFram"
    "ework.Empty\"\000\022J\n\016SendAnnotation\022\033.Nrmk.I"
    "ndyFramework.Message\032\031.Nrmk.IndyFramewor"
    "k.Empty\"\000\022a\n\021PlayTuningProgram\022!.Nrmk.In"
    "dyFramework.TuningProgram\032\'.Nrmk.IndyFra"
    "mework.CollisionThresholds\"\000\022N\n\017PlayProg"
    "ramLine\022\033.Nrmk.IndyFramework.Program\032\034.N"
    "rmk.IndyFramework.Response\"\000\022`\n\031SetModbu"
    "sVariableNameList\022&.Nrmk.IndyFramework.M"
    "odbusVariableList\032\031.Nrmk.IndyFramework.E"
    "mpty\"\000\022O\n\023SetVariableNameList\022\033.Nrmk.Ind"
    "yFramework.AllVars\032\031.Nrmk.IndyFramework."
    "Empty\"\000\022O\n\023GetVariableNameList\022\031.Nrmk.In"
    "dyFramework.Empty\032\033.Nrmk.IndyFramework.A"
    "llVars\"\000\022J\n\016SetIntVariable\022\033.Nrmk.IndyFr"
    "amework.IntVars\032\031.Nrmk.IndyFramework.Emp"
    "ty\"\000\022J\n\016GetIntVariable\022\031.Nrmk.IndyFramew"
    "ork.Empty\032\033.Nrmk.IndyFramework.IntVars\"\000"
    "\022P\n\021SetModbusVariable\022\036.Nrmk.IndyFramewo"
    "rk.ModbusVars\032\031.Nrmk.IndyFramework.Empty"
    "\"\000\022P\n\021GetModbusVariable\022\031.Nrmk.IndyFrame"
    "work.Empty\032\036.Nrmk.IndyFramework.ModbusVa"
    "rs\"\000\022L\n\017SetBoolVariable\022\034.Nrmk.IndyFrame"
    "work.BoolVars\032\031.Nrmk.IndyFramework.Empty"
    "\"\000\022L\n\017GetBoolVariable\022\031.Nrmk.IndyFramewo"
    "rk.Empty\032\034.Nrmk.IndyFramework.BoolVars\"\000"
    "\022N\n\020SetFloatVariable\022\035.Nrmk.IndyFramewor"
    "k.FloatVars\032\031.Nrmk.IndyFramework.Empty\"\000"
    "\022N\n\020GetFloatVariable\022\031.Nrmk.IndyFramewor"
    "k.Empty\032\035.Nrmk.IndyFramework.FloatVars\"\000"
    "\022L\n\017SetJPosVariable\022\034.Nrmk.IndyFramework"
    ".JPosVars\032\031.Nrmk.IndyFramework.Empty\"\000\022L"
    "\n\017GetJPosVariable\022\031.Nrmk.IndyFramework.E"
    "mpty\032\034.Nrmk.IndyFramework.JPosVars\"\000\022L\n\017"
    "SetTPosVariable\022\034.Nrmk.IndyFramework.TPo"
    "sVars\032\031.Nrmk.IndyFramework.Empty\"\000\022L\n\017Ge"
    "tTPosVariable\022\031.Nrmk.IndyFramework.Empty"
    "\032\034.Nrmk.IndyFramework.TPosVars\"\000\022S\n\025SetP"
    "luginBoolVariable\022\035.Nrmk.IndyFramework.N"
    "amedBool\032\031.Nrmk.IndyFramework.Empty\"\000\022R\n"
    "\025GetPluginBoolVariable\022\030.Nrmk.IndyFramew"
    "ork.Name\032\035.Nrmk.IndyFramework.NamedBool\""
    "\000\022Q\n\024SetPluginIntVariable\022\034.Nrmk.IndyFra"
    "mework.NamedInt\032\031.Nrmk.IndyFramework.Emp"
    "ty\"\000\022P\n\024GetPluginIntVariable\022\030.Nrmk.Indy"
    "Framework.Name\032\034.Nrmk.IndyFramework.Name"
    "dInt\"\000\022U\n\026SetPluginFloatVariable\022\036.Nrmk."
    "IndyFramework.NamedFloat\032\031.Nrmk.IndyFram"
    "ework.Empty\"\000\022T\n\026GetPluginFloatVariable\022"
    "\030.Nrmk.IndyFramework.Name\032\036.Nrmk.IndyFra"
    "mework.NamedFloat\"\000\022\\\n\025SetPluginJPosVari"
    "able\022&.Nrmk.IndyFramework.NamedJointPosi"
    "tion\032\031.Nrmk.IndyFramework.Empty\"\000\022[\n\025Get"
    "PluginJPosVariable\022\030.Nrmk.IndyFramework."
    "Name\032&.Nrmk.IndyFramework.NamedJointPosi"
    "tion\"\000\022[\n\025SetPluginTPosVariable\022%.Nrmk.I"
    "ndyFramework.NamedTaskPosition\032\031.Nrmk.In"
    "dyFramework.Empty\"\000\022Z\n\025GetPluginTPosVari"
    "able\022\030.Nrmk.IndyFramework.Name\032%.Nrmk.In"
    "dyFramework.NamedTaskPosition\"\000\022I\n\014PushB"
    "usEvent\022\034.Nrmk.IndyFramework.BusEvent\032\031."
    "Nrmk.IndyFramework.State\"\000\022U\n\rCatchBusEv"
    "ent\022$.Nrmk.IndyFramework.CatchBusEventRe"
    "q\032\034.Nrmk.IndyFramework.BusEvent\"\000\022i\n\021Inv"
    "erseKinematics\022(.Nrmk.IndyFramework.Inve"
    "rseKinematicsReq\032(.Nrmk.IndyFramework.In"
    "verseKinematicsRes\"\000\022i\n\021ForwardKinematic"
    "s\022(.Nrmk.IndyFramework.ForwardKinematics"
    "Req\032(.Nrmk.IndyFramework.ForwardKinemati"
    "csRes\"\000\022~\n\030CheckAproachRetractValid\022/.Nr"
    "mk.IndyFramework.CheckAproachRetractVali"
    "dReq\032/.Nrmk.IndyFramework.CheckAproachRe"
    "tractValidRes\"\000\022l\n\022GetPalletPointList\022)."
    "Nrmk.IndyFramework.GetPalletPointListReq"
    "\032).Nrmk.IndyFramework.GetPalletPointList"
    "Res\"\000\022u\n\025CalculateRelativePose\022,.Nrmk.In"
    "dyFramework.CalculateRelativePoseReq\032,.N"
    "rmk.IndyFramework.CalculateRelativePoseR"
    "es\"\000\022{\n\027CalculateCurrentPoseRel\022..Nrmk.I"
    "ndyFramework.CalculateCurrentPoseRelReq\032"
    "..Nrmk.IndyFramework.CalculateCurrentPos"
    "eRelRes\"\000\022G\n\rPingFromConty\022\031.Nrmk.IndyFr"
    "amework.Empty\032\031.Nrmk.IndyFramework.Empty"
    "\"\000\022P\n\017GetTeleOpDevice\022\031.Nrmk.IndyFramewo"
    "rk.Empty\032 .Nrmk.IndyFramework.TeleOpDevi"
    "ce\"\000\022N\n\016GetTeleOpState\022\031.Nrmk.IndyFramew"
    "ork.Empty\032\037.Nrmk.IndyFramework.TeleOpSta"
    "te\"\000\022W\n\023ConnectTeleOpDevice\022 .Nrmk.IndyF"
    "ramework.TeleOpDevice\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022S\n\026DisConnectTeleOpDevice\022"
    "\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022I\n\017ReadTeleOpInput\022\031."
    "Nrmk.IndyFramework.Empty\032\031.Nrmk.IndyFram"
    "ework.TeleP\"\000\022N\n\013StartTeleOp\022\037.Nrmk.Indy"
    "Framework.TeleOpState\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022G\n\nStopTeleOp\022\031.Nrmk.IndyF"
    "ramework.Empty\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022O\n\013SetPlayRate\022 .Nrmk.IndyFramewo"
    "rk.TelePlayRate\032\034.Nrmk.IndyFramework.Res"
    "ponse\"\000\022L\n\013GetPlayRate\022\031.Nrmk.IndyFramew"
    "ork.Empty\032 .Nrmk.IndyFramework.TelePlayR"
    "ate\"\000\022R\n\017GetTeleFileList\022\031.Nrmk.IndyFram"
    "ework.Empty\032\".Nrmk.IndyFramework.TeleOpF"
    "ileList\"\000\022Q\n\016SaveTeleMotion\022\037.Nrmk.IndyF"
    "ramework.TeleFileReq\032\034.Nrmk.IndyFramewor"
    "k.Response\"\000\022Q\n\016LoadTeleMotion\022\037.Nrmk.In"
    "dyFramework.TeleFileReq\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022S\n\020DeleteTeleMotion\022\037.Nr"
    "mk.IndyFramework.TeleFileReq\032\034.Nrmk.Indy"
    "Framework.Response\"\000\022J\n\rEnableTeleKey\022\031."
    "Nrmk.IndyFramework.State\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022M\n\tMoveTeleJ\022 .Nrmk.Ind"
    "yFramework.MoveTeleJReq\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022M\n\tMoveTeleL\022 .Nrmk.Indy"
    "Framework.MoveTeleLReq\032\034.Nrmk.IndyFramew"
    "ork.Response\"\000\022P\n\014SetForceMode\022 .Nrmk.In"
    "dyFramework.ForceModeReq\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022M\n\014GetForceMode\022\031.Nrmk."
    "IndyFramework.Empty\032 .Nrmk.IndyFramework"
    ".ForceModeReq\"\000\022f\n\032GetTransformedFTSenso"
    "rData\022\031.Nrmk.IndyFramework.Empty\032+.Nrmk."
    "IndyFramework.TransformedFTSensorData\"\000\022"
    "C\n\006FTZero\022\031.Nrmk.IndyFramework.Empty\032\034.N"
    "rmk.IndyFramework.Response\"\000\022G\n\006MoveLF\022\035"
    ".Nrmk.IndyFramework.MoveLFReq\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022f\n\027SetControlInfer"
    "enceData\022+.Nrmk.IndyFramework.ControlInf"
    "erenceDataSet\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022c\n\027GetControlInferenceData\022\031.Nrmk."
    "IndyFramework.Empty\032+.Nrmk.IndyFramework"
    ".ControlInferenceDataSet\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_control_2eproto_deps[3] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_config_5fmsgs_2eproto,
        &::descriptor_table_control_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_control_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_2eproto = {
    false,
    false,
    8514,
    descriptor_table_protodef_control_2eproto,
    "control.proto",
    &descriptor_table_control_2eproto_once,
    descriptor_table_control_2eproto_deps,
    3,
    0,
    schemas,
    file_default_instances,
    TableStruct_control_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_control_2eproto,
    file_level_service_descriptors_control_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_2eproto_getter() {
  return &descriptor_table_control_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_2eproto(&descriptor_table_control_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
