// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cri.proto

#include "cri.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cri_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cri_2eproto = nullptr;
const ::uint32_t TableStruct_cri_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_cri_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\tcri.proto\022\022Nrmk.IndyFramework\032\021common_"
    "msgs.proto\032\016cri_msgs.proto2\341\t\n\003CRI\022J\n\010Lo"
    "ginSFD\022\036.Nrmk.IndyFramework.SFDAccount\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022F\n\tLogout"
    "SFD\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022D\n\nIsSFDLogin\022\031.N"
    "rmk.IndyFramework.Empty\032\031.Nrmk.IndyFrame"
    "work.State\"\000\022R\n\020GenerateSFDToken\022\036.Nrmk."
    "IndyFramework.SFDAccount\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022R\n\020SaveSFDLoginInfo\022\036.N"
    "rmk.IndyFramework.SFDAccount\032\034.Nrmk.Indy"
    "Framework.Response\"\000\022O\n\020LoadSFDLoginInfo"
    "\022\031.Nrmk.IndyFramework.Empty\032\036.Nrmk.IndyF"
    "ramework.SFDAccount\"\000\022N\n\017GetSFDLoginInfo"
    "\022\031.Nrmk.IndyFramework.Empty\032\036.Nrmk.IndyF"
    "ramework.SFDAccount\"\000\022P\n\017SelectSFDTarget"
    "\022\035.Nrmk.IndyFramework.SFDTarget\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022J\n\020IsSFDTargetVa"
    "lid\022\031.Nrmk.IndyFramework.Empty\032\031.Nrmk.In"
    "dyFramework.State\"\000\022J\n\020ReleaseSFDTarget\022"
    "\031.Nrmk.IndyFramework.Empty\032\031.Nrmk.IndyFr"
    "amework.State\"\000\022J\n\014GetSFDTarget\022\031.Nrmk.I"
    "ndyFramework.Empty\032\035.Nrmk.IndyFramework."
    "SFDTarget\"\000\022I\n\014ActiveCRIVel\022\031.Nrmk.IndyF"
    "ramework.State\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022Q\n\016GetSFDProjList\022\031.Nrmk.IndyFram"
    "ework.Empty\032\".Nrmk.IndyFramework.SFDProj"
    "ectList\"\000\022B\n\006GetCRI\022\031.Nrmk.IndyFramework"
    ".Empty\032\033.Nrmk.IndyFramework.CriData\"\000\022P\n"
    "\016SaveSFDAutoSet\022\036.Nrmk.IndyFramework.SFD"
    "AutoSet\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "M\n\016LoadSFDAutoSet\022\031.Nrmk.IndyFramework.E"
    "mpty\032\036.Nrmk.IndyFramework.SFDAutoSet\"\000b\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_cri_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_cri_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_cri_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cri_2eproto = {
    false,
    false,
    1326,
    descriptor_table_protodef_cri_2eproto,
    "cri.proto",
    &descriptor_table_cri_2eproto_once,
    descriptor_table_cri_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_cri_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_cri_2eproto,
    file_level_service_descriptors_cri_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cri_2eproto_getter() {
  return &descriptor_table_cri_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_cri_2eproto(&descriptor_table_cri_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
