// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cri_msgs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cri_5fmsgs_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_cri_5fmsgs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cri_5fmsgs_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cri_5fmsgs_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_cri_5fmsgs_2eproto;
namespace Nrmk {
namespace IndyFramework {
class CriData;
struct CriDataDefaultTypeInternal;
extern CriDataDefaultTypeInternal _CriData_default_instance_;
class SFDAccount;
struct SFDAccountDefaultTypeInternal;
extern SFDAccountDefaultTypeInternal _SFDAccount_default_instance_;
class SFDAutoSet;
struct SFDAutoSetDefaultTypeInternal;
extern SFDAutoSetDefaultTypeInternal _SFDAutoSet_default_instance_;
class SFDProjectList;
struct SFDProjectListDefaultTypeInternal;
extern SFDProjectListDefaultTypeInternal _SFDProjectList_default_instance_;
class SFDTarget;
struct SFDTargetDefaultTypeInternal;
extern SFDTargetDefaultTypeInternal _SFDTarget_default_instance_;
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Nrmk {
namespace IndyFramework {

// ===================================================================


// -------------------------------------------------------------------

class SFDAccount final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDAccount) */ {
 public:
  inline SFDAccount() : SFDAccount(nullptr) {}
  ~SFDAccount() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SFDAccount(::google::protobuf::internal::ConstantInitialized);

  SFDAccount(const SFDAccount& from);
  SFDAccount(SFDAccount&& from) noexcept
    : SFDAccount() {
    *this = ::std::move(from);
  }

  inline SFDAccount& operator=(const SFDAccount& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDAccount& operator=(SFDAccount&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDAccount& default_instance() {
    return *internal_default_instance();
  }
  static inline const SFDAccount* internal_default_instance() {
    return reinterpret_cast<const SFDAccount*>(
               &_SFDAccount_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SFDAccount& a, SFDAccount& b) {
    a.Swap(&b);
  }
  inline void Swap(SFDAccount* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDAccount* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDAccount* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SFDAccount>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDAccount& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SFDAccount& from) {
    SFDAccount::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SFDAccount* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.SFDAccount";
  }
  protected:
  explicit SFDAccount(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmailFieldNumber = 1,
    kTokenFieldNumber = 2,
  };
  // string email = 1;
  void clear_email() ;
  const std::string& email() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* ptr);

  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(
      const std::string& value);
  std::string* _internal_mutable_email();

  public:
  // string token = 2;
  void clear_token() ;
  const std::string& token() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* ptr);

  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(
      const std::string& value);
  std::string* _internal_mutable_token();

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDAccount)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 48, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::google::protobuf::internal::ArenaStringPtr token_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};// -------------------------------------------------------------------

class SFDTarget final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDTarget) */ {
 public:
  inline SFDTarget() : SFDTarget(nullptr) {}
  ~SFDTarget() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SFDTarget(::google::protobuf::internal::ConstantInitialized);

  SFDTarget(const SFDTarget& from);
  SFDTarget(SFDTarget&& from) noexcept
    : SFDTarget() {
    *this = ::std::move(from);
  }

  inline SFDTarget& operator=(const SFDTarget& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDTarget& operator=(SFDTarget&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDTarget& default_instance() {
    return *internal_default_instance();
  }
  static inline const SFDTarget* internal_default_instance() {
    return reinterpret_cast<const SFDTarget*>(
               &_SFDTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SFDTarget& a, SFDTarget& b) {
    a.Swap(&b);
  }
  inline void Swap(SFDTarget* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDTarget* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDTarget* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SFDTarget>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDTarget& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SFDTarget& from) {
    SFDTarget::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SFDTarget* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.SFDTarget";
  }
  protected:
  explicit SFDTarget(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPnFieldNumber = 1,
    kFnFieldNumber = 2,
    kRnFieldNumber = 3,
    kIsoFieldNumber = 4,
  };
  // string pn = 1;
  void clear_pn() ;
  const std::string& pn() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pn(Arg_&& arg, Args_... args);
  std::string* mutable_pn();
  PROTOBUF_NODISCARD std::string* release_pn();
  void set_allocated_pn(std::string* ptr);

  private:
  const std::string& _internal_pn() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pn(
      const std::string& value);
  std::string* _internal_mutable_pn();

  public:
  // string fn = 2;
  void clear_fn() ;
  const std::string& fn() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_fn(Arg_&& arg, Args_... args);
  std::string* mutable_fn();
  PROTOBUF_NODISCARD std::string* release_fn();
  void set_allocated_fn(std::string* ptr);

  private:
  const std::string& _internal_fn() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fn(
      const std::string& value);
  std::string* _internal_mutable_fn();

  public:
  // string rn = 3;
  void clear_rn() ;
  const std::string& rn() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_rn(Arg_&& arg, Args_... args);
  std::string* mutable_rn();
  PROTOBUF_NODISCARD std::string* release_rn();
  void set_allocated_rn(std::string* ptr);

  private:
  const std::string& _internal_rn() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rn(
      const std::string& value);
  std::string* _internal_mutable_rn();

  public:
  // bool iso = 4;
  void clear_iso() ;
  bool iso() const;
  void set_iso(bool value);

  private:
  bool _internal_iso() const;
  void _internal_set_iso(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDTarget)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4, 0, 43, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ArenaStringPtr pn_;
    ::google::protobuf::internal::ArenaStringPtr fn_;
    ::google::protobuf::internal::ArenaStringPtr rn_;
    bool iso_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};// -------------------------------------------------------------------

class CriData final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.CriData) */ {
 public:
  inline CriData() : CriData(nullptr) {}
  ~CriData() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CriData(::google::protobuf::internal::ConstantInitialized);

  CriData(const CriData& from);
  CriData(CriData&& from) noexcept
    : CriData() {
    *this = ::std::move(from);
  }

  inline CriData& operator=(const CriData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CriData& operator=(CriData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CriData& default_instance() {
    return *internal_default_instance();
  }
  static inline const CriData* internal_default_instance() {
    return reinterpret_cast<const CriData*>(
               &_CriData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CriData& a, CriData& b) {
    a.Swap(&b);
  }
  inline void Swap(CriData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CriData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CriData* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CriData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CriData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CriData& from) {
    CriData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CriData* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.CriData";
  }
  protected:
  explicit CriData(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kCriFieldNumber = 2,
    kVelRatioFieldNumber = 3,
  };
  // double time = 1;
  void clear_time() ;
  double time() const;
  void set_time(double value);

  private:
  double _internal_time() const;
  void _internal_set_time(double value);

  public:
  // double cri = 2;
  void clear_cri() ;
  double cri() const;
  void set_cri(double value);

  private:
  double _internal_cri() const;
  void _internal_set_cri(double value);

  public:
  // double velRatio = 3;
  void clear_velratio() ;
  double velratio() const;
  void set_velratio(double value);

  private:
  double _internal_velratio() const;
  void _internal_set_velratio(double value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.CriData)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double time_;
    double cri_;
    double velratio_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};// -------------------------------------------------------------------

class SFDProjectList final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDProjectList) */ {
 public:
  inline SFDProjectList() : SFDProjectList(nullptr) {}
  ~SFDProjectList() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SFDProjectList(::google::protobuf::internal::ConstantInitialized);

  SFDProjectList(const SFDProjectList& from);
  SFDProjectList(SFDProjectList&& from) noexcept
    : SFDProjectList() {
    *this = ::std::move(from);
  }

  inline SFDProjectList& operator=(const SFDProjectList& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDProjectList& operator=(SFDProjectList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDProjectList& default_instance() {
    return *internal_default_instance();
  }
  static inline const SFDProjectList* internal_default_instance() {
    return reinterpret_cast<const SFDProjectList*>(
               &_SFDProjectList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SFDProjectList& a, SFDProjectList& b) {
    a.Swap(&b);
  }
  inline void Swap(SFDProjectList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDProjectList* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDProjectList* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SFDProjectList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDProjectList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SFDProjectList& from) {
    SFDProjectList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SFDProjectList* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.SFDProjectList";
  }
  protected:
  explicit SFDProjectList(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 1,
  };
  // string list = 1;
  void clear_list() ;
  const std::string& list() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_list(Arg_&& arg, Args_... args);
  std::string* mutable_list();
  PROTOBUF_NODISCARD std::string* release_list();
  void set_allocated_list(std::string* ptr);

  private:
  const std::string& _internal_list() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_list(
      const std::string& value);
  std::string* _internal_mutable_list();

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDProjectList)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 46, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ArenaStringPtr list_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};// -------------------------------------------------------------------

class SFDAutoSet final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.SFDAutoSet) */ {
 public:
  inline SFDAutoSet() : SFDAutoSet(nullptr) {}
  ~SFDAutoSet() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SFDAutoSet(::google::protobuf::internal::ConstantInitialized);

  SFDAutoSet(const SFDAutoSet& from);
  SFDAutoSet(SFDAutoSet&& from) noexcept
    : SFDAutoSet() {
    *this = ::std::move(from);
  }

  inline SFDAutoSet& operator=(const SFDAutoSet& from) {
    CopyFrom(from);
    return *this;
  }
  inline SFDAutoSet& operator=(SFDAutoSet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SFDAutoSet& default_instance() {
    return *internal_default_instance();
  }
  static inline const SFDAutoSet* internal_default_instance() {
    return reinterpret_cast<const SFDAutoSet*>(
               &_SFDAutoSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SFDAutoSet& a, SFDAutoSet& b) {
    a.Swap(&b);
  }
  inline void Swap(SFDAutoSet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SFDAutoSet* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SFDAutoSet* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SFDAutoSet>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SFDAutoSet& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SFDAutoSet& from) {
    SFDAutoSet::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SFDAutoSet* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.SFDAutoSet";
  }
  protected:
  explicit SFDAutoSet(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPnFieldNumber = 2,
    kFnFieldNumber = 3,
    kRnFieldNumber = 4,
    kLoginFieldNumber = 1,
    kIsoFieldNumber = 5,
  };
  // string pn = 2;
  void clear_pn() ;
  const std::string& pn() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pn(Arg_&& arg, Args_... args);
  std::string* mutable_pn();
  PROTOBUF_NODISCARD std::string* release_pn();
  void set_allocated_pn(std::string* ptr);

  private:
  const std::string& _internal_pn() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pn(
      const std::string& value);
  std::string* _internal_mutable_pn();

  public:
  // string fn = 3;
  void clear_fn() ;
  const std::string& fn() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_fn(Arg_&& arg, Args_... args);
  std::string* mutable_fn();
  PROTOBUF_NODISCARD std::string* release_fn();
  void set_allocated_fn(std::string* ptr);

  private:
  const std::string& _internal_fn() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fn(
      const std::string& value);
  std::string* _internal_mutable_fn();

  public:
  // string rn = 4;
  void clear_rn() ;
  const std::string& rn() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_rn(Arg_&& arg, Args_... args);
  std::string* mutable_rn();
  PROTOBUF_NODISCARD std::string* release_rn();
  void set_allocated_rn(std::string* ptr);

  private:
  const std::string& _internal_rn() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rn(
      const std::string& value);
  std::string* _internal_mutable_rn();

  public:
  // bool login = 1;
  void clear_login() ;
  bool login() const;
  void set_login(bool value);

  private:
  bool _internal_login() const;
  void _internal_set_login(bool value);

  public:
  // bool iso = 5;
  void clear_iso() ;
  bool iso() const;
  void set_iso(bool value);

  private:
  bool _internal_iso() const;
  void _internal_set_iso(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.SFDAutoSet)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5, 0, 44, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ArenaStringPtr pn_;
    ::google::protobuf::internal::ArenaStringPtr fn_;
    ::google::protobuf::internal::ArenaStringPtr rn_;
    bool login_;
    bool iso_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cri_5fmsgs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SFDAccount

// string email = 1;
inline void SFDAccount::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& SFDAccount::email() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAccount.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDAccount::set_email(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAccount.email)
}
inline std::string* SFDAccount::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAccount.email)
  return _s;
}
inline const std::string& SFDAccount::_internal_email() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.email_.Get();
}
inline void SFDAccount::_internal_set_email(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDAccount::_internal_mutable_email() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.email_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDAccount::release_email() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAccount.email)
  return _impl_.email_.Release();
}
inline void SFDAccount::set_allocated_email(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.email_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.email_.IsDefault()) {
          _impl_.email_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAccount.email)
}

// string token = 2;
inline void SFDAccount::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& SFDAccount::token() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAccount.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDAccount::set_token(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAccount.token)
}
inline std::string* SFDAccount::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAccount.token)
  return _s;
}
inline const std::string& SFDAccount::_internal_token() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.token_.Get();
}
inline void SFDAccount::_internal_set_token(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDAccount::_internal_mutable_token() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.token_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDAccount::release_token() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAccount.token)
  return _impl_.token_.Release();
}
inline void SFDAccount::set_allocated_token(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.token_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.token_.IsDefault()) {
          _impl_.token_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAccount.token)
}

// -------------------------------------------------------------------

// SFDTarget

// string pn = 1;
inline void SFDTarget::clear_pn() {
  _impl_.pn_.ClearToEmpty();
}
inline const std::string& SFDTarget::pn() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.pn)
  return _internal_pn();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDTarget::set_pn(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pn_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.pn)
}
inline std::string* SFDTarget::mutable_pn() {
  std::string* _s = _internal_mutable_pn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDTarget.pn)
  return _s;
}
inline const std::string& SFDTarget::_internal_pn() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.pn_.Get();
}
inline void SFDTarget::_internal_set_pn(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pn_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDTarget::_internal_mutable_pn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.pn_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDTarget::release_pn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDTarget.pn)
  return _impl_.pn_.Release();
}
inline void SFDTarget::set_allocated_pn(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.pn_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pn_.IsDefault()) {
          _impl_.pn_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDTarget.pn)
}

// string fn = 2;
inline void SFDTarget::clear_fn() {
  _impl_.fn_.ClearToEmpty();
}
inline const std::string& SFDTarget::fn() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.fn)
  return _internal_fn();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDTarget::set_fn(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.fn_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.fn)
}
inline std::string* SFDTarget::mutable_fn() {
  std::string* _s = _internal_mutable_fn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDTarget.fn)
  return _s;
}
inline const std::string& SFDTarget::_internal_fn() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.fn_.Get();
}
inline void SFDTarget::_internal_set_fn(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.fn_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDTarget::_internal_mutable_fn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.fn_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDTarget::release_fn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDTarget.fn)
  return _impl_.fn_.Release();
}
inline void SFDTarget::set_allocated_fn(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.fn_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.fn_.IsDefault()) {
          _impl_.fn_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDTarget.fn)
}

// string rn = 3;
inline void SFDTarget::clear_rn() {
  _impl_.rn_.ClearToEmpty();
}
inline const std::string& SFDTarget::rn() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.rn)
  return _internal_rn();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDTarget::set_rn(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rn_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.rn)
}
inline std::string* SFDTarget::mutable_rn() {
  std::string* _s = _internal_mutable_rn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDTarget.rn)
  return _s;
}
inline const std::string& SFDTarget::_internal_rn() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rn_.Get();
}
inline void SFDTarget::_internal_set_rn(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rn_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDTarget::_internal_mutable_rn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.rn_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDTarget::release_rn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDTarget.rn)
  return _impl_.rn_.Release();
}
inline void SFDTarget::set_allocated_rn(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rn_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.rn_.IsDefault()) {
          _impl_.rn_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDTarget.rn)
}

// bool iso = 4;
inline void SFDTarget::clear_iso() {
  _impl_.iso_ = false;
}
inline bool SFDTarget::iso() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDTarget.iso)
  return _internal_iso();
}
inline void SFDTarget::set_iso(bool value) {
  _internal_set_iso(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDTarget.iso)
}
inline bool SFDTarget::_internal_iso() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.iso_;
}
inline void SFDTarget::_internal_set_iso(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.iso_ = value;
}

// -------------------------------------------------------------------

// CriData

// double time = 1;
inline void CriData::clear_time() {
  _impl_.time_ = 0;
}
inline double CriData::time() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.CriData.time)
  return _internal_time();
}
inline void CriData::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.CriData.time)
}
inline double CriData::_internal_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.time_;
}
inline void CriData::_internal_set_time(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.time_ = value;
}

// double cri = 2;
inline void CriData::clear_cri() {
  _impl_.cri_ = 0;
}
inline double CriData::cri() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.CriData.cri)
  return _internal_cri();
}
inline void CriData::set_cri(double value) {
  _internal_set_cri(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.CriData.cri)
}
inline double CriData::_internal_cri() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.cri_;
}
inline void CriData::_internal_set_cri(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.cri_ = value;
}

// double velRatio = 3;
inline void CriData::clear_velratio() {
  _impl_.velratio_ = 0;
}
inline double CriData::velratio() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.CriData.velRatio)
  return _internal_velratio();
}
inline void CriData::set_velratio(double value) {
  _internal_set_velratio(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.CriData.velRatio)
}
inline double CriData::_internal_velratio() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.velratio_;
}
inline void CriData::_internal_set_velratio(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.velratio_ = value;
}

// -------------------------------------------------------------------

// SFDProjectList

// string list = 1;
inline void SFDProjectList::clear_list() {
  _impl_.list_.ClearToEmpty();
}
inline const std::string& SFDProjectList::list() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDProjectList.list)
  return _internal_list();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDProjectList::set_list(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.list_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDProjectList.list)
}
inline std::string* SFDProjectList::mutable_list() {
  std::string* _s = _internal_mutable_list();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDProjectList.list)
  return _s;
}
inline const std::string& SFDProjectList::_internal_list() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.list_.Get();
}
inline void SFDProjectList::_internal_set_list(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.list_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDProjectList::_internal_mutable_list() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.list_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDProjectList::release_list() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDProjectList.list)
  return _impl_.list_.Release();
}
inline void SFDProjectList::set_allocated_list(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.list_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.list_.IsDefault()) {
          _impl_.list_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDProjectList.list)
}

// -------------------------------------------------------------------

// SFDAutoSet

// bool login = 1;
inline void SFDAutoSet::clear_login() {
  _impl_.login_ = false;
}
inline bool SFDAutoSet::login() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.login)
  return _internal_login();
}
inline void SFDAutoSet::set_login(bool value) {
  _internal_set_login(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.login)
}
inline bool SFDAutoSet::_internal_login() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.login_;
}
inline void SFDAutoSet::_internal_set_login(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.login_ = value;
}

// string pn = 2;
inline void SFDAutoSet::clear_pn() {
  _impl_.pn_.ClearToEmpty();
}
inline const std::string& SFDAutoSet::pn() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.pn)
  return _internal_pn();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDAutoSet::set_pn(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pn_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.pn)
}
inline std::string* SFDAutoSet::mutable_pn() {
  std::string* _s = _internal_mutable_pn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAutoSet.pn)
  return _s;
}
inline const std::string& SFDAutoSet::_internal_pn() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.pn_.Get();
}
inline void SFDAutoSet::_internal_set_pn(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pn_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDAutoSet::_internal_mutable_pn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.pn_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDAutoSet::release_pn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAutoSet.pn)
  return _impl_.pn_.Release();
}
inline void SFDAutoSet::set_allocated_pn(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.pn_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pn_.IsDefault()) {
          _impl_.pn_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAutoSet.pn)
}

// string fn = 3;
inline void SFDAutoSet::clear_fn() {
  _impl_.fn_.ClearToEmpty();
}
inline const std::string& SFDAutoSet::fn() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.fn)
  return _internal_fn();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDAutoSet::set_fn(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.fn_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.fn)
}
inline std::string* SFDAutoSet::mutable_fn() {
  std::string* _s = _internal_mutable_fn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAutoSet.fn)
  return _s;
}
inline const std::string& SFDAutoSet::_internal_fn() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.fn_.Get();
}
inline void SFDAutoSet::_internal_set_fn(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.fn_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDAutoSet::_internal_mutable_fn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.fn_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDAutoSet::release_fn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAutoSet.fn)
  return _impl_.fn_.Release();
}
inline void SFDAutoSet::set_allocated_fn(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.fn_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.fn_.IsDefault()) {
          _impl_.fn_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAutoSet.fn)
}

// string rn = 4;
inline void SFDAutoSet::clear_rn() {
  _impl_.rn_.ClearToEmpty();
}
inline const std::string& SFDAutoSet::rn() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.rn)
  return _internal_rn();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SFDAutoSet::set_rn(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rn_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.rn)
}
inline std::string* SFDAutoSet::mutable_rn() {
  std::string* _s = _internal_mutable_rn();
  // @@protoc_insertion_point(field_mutable:Nrmk.IndyFramework.SFDAutoSet.rn)
  return _s;
}
inline const std::string& SFDAutoSet::_internal_rn() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rn_.Get();
}
inline void SFDAutoSet::_internal_set_rn(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rn_.Set(value, GetArenaForAllocation());
}
inline std::string* SFDAutoSet::_internal_mutable_rn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.rn_.Mutable( GetArenaForAllocation());
}
inline std::string* SFDAutoSet::release_rn() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Nrmk.IndyFramework.SFDAutoSet.rn)
  return _impl_.rn_.Release();
}
inline void SFDAutoSet::set_allocated_rn(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rn_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.rn_.IsDefault()) {
          _impl_.rn_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Nrmk.IndyFramework.SFDAutoSet.rn)
}

// bool iso = 5;
inline void SFDAutoSet::clear_iso() {
  _impl_.iso_ = false;
}
inline bool SFDAutoSet::iso() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.SFDAutoSet.iso)
  return _internal_iso();
}
inline void SFDAutoSet::set_iso(bool value) {
  _internal_set_iso(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.SFDAutoSet.iso)
}
inline bool SFDAutoSet::_internal_iso() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.iso_;
}
inline void SFDAutoSet::_internal_set_iso(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.iso_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_cri_5fmsgs_2eproto_2epb_2eh
