// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethercat.proto

#include "ethercat.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ethercat_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ethercat_2eproto = nullptr;
const ::uint32_t TableStruct_ethercat_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_ethercat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016ethercat.proto\022\022Nrmk.IndyFramework\032\023et"
    "hercat_msgs.proto\032\021common_msgs.proto2\325\036\n"
    "\010EtherCAT\022P\n\017SetMasterStatus\022 .Nrmk.Indy"
    "Framework.MasterStatus\032\031.Nrmk.IndyFramew"
    "ork.Empty\"\000\022P\n\017GetMasterStatus\022\031.Nrmk.In"
    "dyFramework.Empty\032 .Nrmk.IndyFramework.M"
    "asterStatus\"\000\022N\n\016GetSlaveStatus\022\031.Nrmk.I"
    "ndyFramework.Empty\032\037.Nrmk.IndyFramework."
    "SlaveStatus\"\000\022V\n\021GetRxDomainStatus\022\031.Nrm"
    "k.IndyFramework.Empty\032$.Nrmk.IndyFramewo"
    "rk.EcatDomainStatus\"\000\022V\n\021GetTxDomainStat"
    "us\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.Ind"
    "yFramework.EcatDomainStatus\"\000\022Q\n\rIsSyste"
    "mReady\022\031.Nrmk.IndyFramework.Empty\032#.Nrmk"
    ".IndyFramework.EcatSystemReady\"\000\022I\n\tIsSe"
    "rvoOn\022\031.Nrmk.IndyFramework.Empty\032\037.Nrmk."
    "IndyFramework.EcatServoOn\"\000\022P\n\017GetSlaveT"
    "ypeNum\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk"
    ".IndyFramework.SlaveTypeNum\"\000\022L\n\022ResetOv"
    "erflowCount\022\031.Nrmk.IndyFramework.Empty\032\031"
    ".Nrmk.IndyFramework.Empty\"\000\022K\n\nSetServoR"
    "x\022 .Nrmk.IndyFramework.ServoRxIndex\032\031.Nr"
    "mk.IndyFramework.Empty\"\000\022K\n\nGetServoRx\022\036"
    ".Nrmk.IndyFramework.ServoIndex\032\033.Nrmk.In"
    "dyFramework.ServoRx\"\000\022K\n\nGetServoTx\022\036.Nr"
    "mk.IndyFramework.ServoIndex\032\033.Nrmk.IndyF"
    "ramework.ServoTx\"\000\022S\n\016SetServoRxKeba\022$.N"
    "rmk.IndyFramework.ServoRxIndexKeba\032\031.Nrm"
    "k.IndyFramework.Empty\"\000\022S\n\016GetServoRxKeb"
    "a\022\036.Nrmk.IndyFramework.ServoIndex\032\037.Nrmk"
    ".IndyFramework.ServoRxKeba\"\000\022S\n\016GetServo"
    "TxKeba\022\036.Nrmk.IndyFramework.ServoIndex\032\037"
    ".Nrmk.IndyFramework.ServoTxKeba\"\000\022I\n\nSet"
    "ServoOn\022\036.Nrmk.IndyFramework.ServoIndex\032"
    "\031.Nrmk.IndyFramework.Empty\"\000\022J\n\013SetServo"
    "Off\022\036.Nrmk.IndyFramework.ServoIndex\032\031.Nr"
    "mk.IndyFramework.Empty\"\000\022V\n\023GetServoTemp"
    "erature\022\036.Nrmk.IndyFramework.ServoIndex\032"
    "\035.Nrmk.IndyFramework.ServoTemp\"\000\022U\n\021GetS"
    "ervoErrorCode\022\036.Nrmk.IndyFramework.Servo"
    "Index\032\036.Nrmk.IndyFramework.ServoError\"\000\022"
    "I\n\nResetServo\022\036.Nrmk.IndyFramework.Servo"
    "Index\032\031.Nrmk.IndyFramework.Empty\"\000\022Q\n\022Se"
    "tCOREManualBrake\022\036.Nrmk.IndyFramework.Se"
    "rvoBrake\032\031.Nrmk.IndyFramework.Empty\"\000\022J\n"
    "\014SetEndtoolRx\022\035.Nrmk.IndyFramework.Endto"
    "olRx\032\031.Nrmk.IndyFramework.Empty\"\000\022J\n\014Get"
    "EndtoolRx\022\031.Nrmk.IndyFramework.Empty\032\035.N"
    "rmk.IndyFramework.EndtoolRx\"\000\022J\n\014GetEndt"
    "oolTx\022\031.Nrmk.IndyFramework.Empty\032\035.Nrmk."
    "IndyFramework.EndtoolTx\"\000\022X\n\023GetEndtoolD"
    "ockingTx\022\031.Nrmk.IndyFramework.Empty\032$.Nr"
    "mk.IndyFramework.EndtoolDockingTx\"\000\022T\n\021S"
    "etEndtoolRS485Rx\022\".Nrmk.IndyFramework.En"
    "dtoolRS485Rx\032\031.Nrmk.IndyFramework.Empty\""
    "\000\022T\n\021GetEndtoolRS485Rx\022\031.Nrmk.IndyFramew"
    "ork.Empty\032\".Nrmk.IndyFramework.EndtoolRS"
    "485Rx\"\000\022T\n\021GetEndtoolRS485Tx\022\031.Nrmk.Indy"
    "Framework.Empty\032\".Nrmk.IndyFramework.End"
    "toolRS485Tx\"\000\022K\n\020SetEndtoolLedDim\022\032.Nrmk"
    ".IndyFramework.LedDim\032\031.Nrmk.IndyFramewo"
    "rk.Empty\"\000\022T\n\021SetSRKeyEndtoolRx\022\".Nrmk.I"
    "ndyFramework.SRKeyEndtoolRx\032\031.Nrmk.IndyF"
    "ramework.Empty\"\000\022T\n\021GetSRKeyEndtoolRx\022\031."
    "Nrmk.IndyFramework.Empty\032\".Nrmk.IndyFram"
    "ework.SRKeyEndtoolRx\"\000\022T\n\021GetSRKeyEndtoo"
    "lTx\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk.In"
    "dyFramework.SRKeyEndtoolTx\"\000\022J\n\014SetIOBoa"
    "rdRx\022\035.Nrmk.IndyFramework.IOBoardRx\032\031.Nr"
    "mk.IndyFramework.Empty\"\000\022J\n\014GetIOBoardTx"
    "\022\031.Nrmk.IndyFramework.Empty\032\035.Nrmk.IndyF"
    "ramework.IOBoardTx\"\000\022J\n\014GetIOBoardRx\022\031.N"
    "rmk.IndyFramework.Empty\032\035.Nrmk.IndyFrame"
    "work.IOBoardRx\"\000\022L\n\005GetDI\022\034.Nrmk.IndyFra"
    "mework.DIOIndex\032#.Nrmk.IndyFramework.DIO"
    "DigitalInput\"\000\022M\n\005GetDO\022\034.Nrmk.IndyFrame"
    "work.DIOIndex\032$.Nrmk.IndyFramework.DIODi"
    "gitalOutput\"\000\022J\n\005SetDO\022$.Nrmk.IndyFramew"
    "ork.DIODigitalOutput\032\031.Nrmk.IndyFramewor"
    "k.Empty\"\000\022Q\n\017GetMaxTorqueSDO\022\035.Nrmk.Indy"
    "Framework.EcatIndex\032\035.Nrmk.IndyFramework"
    ".SDOIntVal\"\000\022R\n\020GetProfileVelSDO\022\035.Nrmk."
    "IndyFramework.EcatIndex\032\035.Nrmk.IndyFrame"
    "work.SDOIntVal\"\000\022R\n\020GetProfileAccSDO\022\035.N"
    "rmk.IndyFramework.EcatIndex\032\035.Nrmk.IndyF"
    "ramework.SDOIntVal\"\000\022R\n\020GetProfileDecSDO"
    "\022\035.Nrmk.IndyFramework.EcatIndex\032\035.Nrmk.I"
    "ndyFramework.SDOIntVal\"\000\022N\n\017SetMaxTorque"
    "SDO\022\036.Nrmk.IndyFramework.ServoParam\032\031.Nr"
    "mk.IndyFramework.Empty\"\000\022O\n\020SetProfileVe"
    "lSDO\022\036.Nrmk.IndyFramework.ServoParam\032\031.N"
    "rmk.IndyFramework.Empty\"\000\022O\n\020SetProfileA"
    "ccSDO\022\036.Nrmk.IndyFramework.ServoParam\032\031."
    "Nrmk.IndyFramework.Empty\"\000\022O\n\020SetProfile"
    "DecSDO\022\036.Nrmk.IndyFramework.ServoParam\032\031"
    ".Nrmk.IndyFramework.Empty\"\000\022Y\n\021GetRobotZ"
    "eroCount\022\036.Nrmk.IndyFramework.ServoIndex"
    "\032\".Nrmk.IndyFramework.RobotZeroCount\"\000\022T"
    "\n\025SetRobotZeroAsCurrent\022\036.Nrmk.IndyFrame"
    "work.ServoIndex\032\031.Nrmk.IndyFramework.Emp"
    "ty\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ethercat_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_ethercat_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_ethercat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ethercat_2eproto = {
    false,
    false,
    4012,
    descriptor_table_protodef_ethercat_2eproto,
    "ethercat.proto",
    &descriptor_table_ethercat_2eproto_once,
    descriptor_table_ethercat_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_ethercat_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_ethercat_2eproto,
    file_level_service_descriptors_ethercat_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ethercat_2eproto_getter() {
  return &descriptor_table_ethercat_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ethercat_2eproto(&descriptor_table_ethercat_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
