// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: linear.proto

#include "linear.pb.h"
#include "linear.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Nrmk {
namespace IndyFramework {

static const char* LinearControl_method_names[] = {
  "/Nrmk.IndyFramework.LinearControl/SetServoAll",
  "/Nrmk.IndyFramework.LinearControl/MoveLinear",
  "/Nrmk.IndyFramework.LinearControl/StopMotion",
  "/Nrmk.IndyFramework.LinearControl/PauseMotion",
  "/Nrmk.IndyFramework.LinearControl/ResumeMotion",
  "/Nrmk.IndyFramework.LinearControl/GetAxesInfo",
  "/Nrmk.IndyFramework.LinearControl/SetTargetTorque",
  "/Nrmk.IndyFramework.LinearControl/SetControlGains",
  "/Nrmk.IndyFramework.LinearControl/GetControlGains",
  "/Nrmk.IndyFramework.LinearControl/SetZeroPosition",
  "/Nrmk.IndyFramework.LinearControl/GetZeroPosition",
};

std::unique_ptr< LinearControl::Stub> LinearControl::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LinearControl::Stub> stub(new LinearControl::Stub(channel, options));
  return stub;
}

LinearControl::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetServoAll_(LinearControl_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MoveLinear_(LinearControl_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopMotion_(LinearControl_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PauseMotion_(LinearControl_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResumeMotion_(LinearControl_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAxesInfo_(LinearControl_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTargetTorque_(LinearControl_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetControlGains_(LinearControl_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetControlGains_(LinearControl_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetZeroPosition_(LinearControl_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetZeroPosition_(LinearControl_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LinearControl::Stub::SetServoAll(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::State& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::State, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetServoAll_, context, request, response);
}

void LinearControl::Stub::async::SetServoAll(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::State* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::State, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetServoAll_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::SetServoAll(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::State* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetServoAll_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncSetServoAllRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::State& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::State, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetServoAll_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncSetServoAllRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::State& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetServoAllRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::MoveLinear(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearTarget& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::LinearTarget, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MoveLinear_, context, request, response);
}

void LinearControl::Stub::async::MoveLinear(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearTarget* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::LinearTarget, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MoveLinear_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::MoveLinear(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearTarget* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MoveLinear_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncMoveLinearRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearTarget& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::LinearTarget, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MoveLinear_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncMoveLinearRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearTarget& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMoveLinearRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::StopMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::StopCat& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::StopCat, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopMotion_, context, request, response);
}

void LinearControl::Stub::async::StopMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::StopCat* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::StopCat, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopMotion_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::StopMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::StopCat* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopMotion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncStopMotionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::StopCat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::StopCat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopMotion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncStopMotionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::StopCat& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopMotionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::PauseMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::PauseCat& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::PauseCat, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PauseMotion_, context, request, response);
}

void LinearControl::Stub::async::PauseMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::PauseCat* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::PauseCat, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PauseMotion_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::PauseMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::PauseCat* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PauseMotion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncPauseMotionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::PauseCat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::PauseCat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PauseMotion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncPauseMotionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::PauseCat& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPauseMotionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::ResumeMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResumeMotion_, context, request, response);
}

void LinearControl::Stub::async::ResumeMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResumeMotion_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::ResumeMotion(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResumeMotion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncResumeMotionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResumeMotion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncResumeMotionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResumeMotionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::GetAxesInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::AxesInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::AxesInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAxesInfo_, context, request, response);
}

void LinearControl::Stub::async::GetAxesInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::AxesInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::AxesInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAxesInfo_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::GetAxesInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::AxesInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAxesInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::AxesInfo>* LinearControl::Stub::PrepareAsyncGetAxesInfoRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::AxesInfo, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAxesInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::AxesInfo>* LinearControl::Stub::AsyncGetAxesInfoRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAxesInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::SetTargetTorque(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::TargetTorque& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::TargetTorque, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTargetTorque_, context, request, response);
}

void LinearControl::Stub::async::SetTargetTorque(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::TargetTorque* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::TargetTorque, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTargetTorque_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::SetTargetTorque(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::TargetTorque* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTargetTorque_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncSetTargetTorqueRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::TargetTorque& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::TargetTorque, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTargetTorque_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncSetTargetTorqueRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::TargetTorque& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTargetTorqueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::SetControlGains(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ControlGains& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::ControlGains, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetControlGains_, context, request, response);
}

void LinearControl::Stub::async::SetControlGains(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ControlGains* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::ControlGains, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetControlGains_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::SetControlGains(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ControlGains* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetControlGains_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncSetControlGainsRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ControlGains& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::ControlGains, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetControlGains_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncSetControlGainsRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ControlGains& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetControlGainsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::GetControlGains(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Index& request, ::Nrmk::IndyFramework::ControlGains* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Index, ::Nrmk::IndyFramework::ControlGains, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetControlGains_, context, request, response);
}

void LinearControl::Stub::async::GetControlGains(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Index* request, ::Nrmk::IndyFramework::ControlGains* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Index, ::Nrmk::IndyFramework::ControlGains, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetControlGains_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::GetControlGains(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Index* request, ::Nrmk::IndyFramework::ControlGains* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetControlGains_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ControlGains>* LinearControl::Stub::PrepareAsyncGetControlGainsRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Index& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::ControlGains, ::Nrmk::IndyFramework::Index, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetControlGains_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ControlGains>* LinearControl::Stub::AsyncGetControlGainsRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Index& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetControlGainsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::SetZeroPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearAxisServoData& request, ::Nrmk::IndyFramework::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::LinearAxisServoData, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetZeroPosition_, context, request, response);
}

void LinearControl::Stub::async::SetZeroPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearAxisServoData* request, ::Nrmk::IndyFramework::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::LinearAxisServoData, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetZeroPosition_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::SetZeroPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearAxisServoData* request, ::Nrmk::IndyFramework::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetZeroPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::PrepareAsyncSetZeroPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearAxisServoData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Response, ::Nrmk::IndyFramework::LinearAxisServoData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetZeroPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Response>* LinearControl::Stub::AsyncSetZeroPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::LinearAxisServoData& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetZeroPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LinearControl::Stub::GetZeroPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::LinearAxisServoData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::LinearAxisServoData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetZeroPosition_, context, request, response);
}

void LinearControl::Stub::async::GetZeroPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::LinearAxisServoData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::LinearAxisServoData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetZeroPosition_, context, request, response, std::move(f));
}

void LinearControl::Stub::async::GetZeroPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::LinearAxisServoData* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetZeroPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::LinearAxisServoData>* LinearControl::Stub::PrepareAsyncGetZeroPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::LinearAxisServoData, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetZeroPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::LinearAxisServoData>* LinearControl::Stub::AsyncGetZeroPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetZeroPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

LinearControl::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::State, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::State* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->SetServoAll(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::LinearTarget, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::LinearTarget* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->MoveLinear(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::StopCat, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::StopCat* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->StopMotion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::PauseCat, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::PauseCat* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->PauseMotion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->ResumeMotion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::AxesInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::AxesInfo* resp) {
               return service->GetAxesInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::TargetTorque, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::TargetTorque* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->SetTargetTorque(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::ControlGains, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::ControlGains* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->SetControlGains(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::Index, ::Nrmk::IndyFramework::ControlGains, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Index* req,
             ::Nrmk::IndyFramework::ControlGains* resp) {
               return service->GetControlGains(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::LinearAxisServoData, ::Nrmk::IndyFramework::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::LinearAxisServoData* req,
             ::Nrmk::IndyFramework::Response* resp) {
               return service->SetZeroPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LinearControl_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LinearControl::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::LinearAxisServoData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LinearControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::LinearAxisServoData* resp) {
               return service->GetZeroPosition(ctx, req, resp);
             }, this)));
}

LinearControl::Service::~Service() {
}

::grpc::Status LinearControl::Service::SetServoAll(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::State* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::MoveLinear(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::LinearTarget* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::StopMotion(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::StopCat* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::PauseMotion(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::PauseCat* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::ResumeMotion(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::GetAxesInfo(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::AxesInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::SetTargetTorque(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::TargetTorque* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::SetControlGains(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::ControlGains* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::GetControlGains(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Index* request, ::Nrmk::IndyFramework::ControlGains* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::SetZeroPosition(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::LinearAxisServoData* request, ::Nrmk::IndyFramework::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LinearControl::Service::GetZeroPosition(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::LinearAxisServoData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Nrmk
}  // namespace IndyFramework

