// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_linear_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_linear_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "common_msgs.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_linear_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_linear_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_linear_2eproto;
namespace Nrmk {
namespace IndyFramework {
class AxesInfo;
struct AxesInfoDefaultTypeInternal;
extern AxesInfoDefaultTypeInternal _AxesInfo_default_instance_;
class ControlGains;
struct ControlGainsDefaultTypeInternal;
extern ControlGainsDefaultTypeInternal _ControlGains_default_instance_;
class Index;
struct IndexDefaultTypeInternal;
extern IndexDefaultTypeInternal _Index_default_instance_;
class LinearAxisServoData;
struct LinearAxisServoDataDefaultTypeInternal;
extern LinearAxisServoDataDefaultTypeInternal _LinearAxisServoData_default_instance_;
class LinearTarget;
struct LinearTargetDefaultTypeInternal;
extern LinearTargetDefaultTypeInternal _LinearTarget_default_instance_;
class TargetTorque;
struct TargetTorqueDefaultTypeInternal;
extern TargetTorqueDefaultTypeInternal _TargetTorque_default_instance_;
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Nrmk {
namespace IndyFramework {
enum AxesInfo_OpState : int {
  AxesInfo_OpState_SYSTEM_OFF = 0,
  AxesInfo_OpState_SYSTEM_ON = 1,
  AxesInfo_OpState_VIOLATE = 2,
  AxesInfo_OpState_RECOVER_HARD = 3,
  AxesInfo_OpState_RECOVER_SOFT = 4,
  AxesInfo_OpState_IDLE = 5,
  AxesInfo_OpState_MOVING = 6,
  AxesInfo_OpState_PAUSING = 7,
  AxesInfo_OpState_COLLISION_PAUSE = 8,
  AxesInfo_OpState_COLLISION_STOP = 9,
  AxesInfo_OpState_AxesInfo_OpState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AxesInfo_OpState_AxesInfo_OpState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AxesInfo_OpState_IsValid(int value);
constexpr AxesInfo_OpState AxesInfo_OpState_OpState_MIN = static_cast<AxesInfo_OpState>(0);
constexpr AxesInfo_OpState AxesInfo_OpState_OpState_MAX = static_cast<AxesInfo_OpState>(9);
constexpr int AxesInfo_OpState_OpState_ARRAYSIZE = 9 + 1;
const ::google::protobuf::EnumDescriptor*
AxesInfo_OpState_descriptor();
template <typename T>
const std::string& AxesInfo_OpState_Name(T value) {
  static_assert(std::is_same<T, AxesInfo_OpState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OpState_Name().");
  return AxesInfo_OpState_Name(static_cast<AxesInfo_OpState>(value));
}
template <>
inline const std::string& AxesInfo_OpState_Name(AxesInfo_OpState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AxesInfo_OpState_descriptor,
                                                 0, 9>(
      static_cast<int>(value));
}
inline bool AxesInfo_OpState_Parse(absl::string_view name, AxesInfo_OpState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AxesInfo_OpState>(
      AxesInfo_OpState_descriptor(), name, value);
}
enum AxesInfo_TrajState : int {
  AxesInfo_TrajState_TRAJ_NONE = 0,
  AxesInfo_TrajState_TRAJ_INIT = 1,
  AxesInfo_TrajState_TRAJ_CALC = 2,
  AxesInfo_TrajState_TRAJ_STBY = 3,
  AxesInfo_TrajState_TRAJ_ACC = 4,
  AxesInfo_TrajState_TRAJ_CRZ = 5,
  AxesInfo_TrajState_TRAJ_DEC = 6,
  AxesInfo_TrajState_TRAJ_CANC = 7,
  AxesInfo_TrajState_TRAJ_FIN = 8,
  AxesInfo_TrajState_TRAJ_ERR = 9,
  AxesInfo_TrajState_AxesInfo_TrajState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AxesInfo_TrajState_AxesInfo_TrajState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AxesInfo_TrajState_IsValid(int value);
constexpr AxesInfo_TrajState AxesInfo_TrajState_TrajState_MIN = static_cast<AxesInfo_TrajState>(0);
constexpr AxesInfo_TrajState AxesInfo_TrajState_TrajState_MAX = static_cast<AxesInfo_TrajState>(9);
constexpr int AxesInfo_TrajState_TrajState_ARRAYSIZE = 9 + 1;
const ::google::protobuf::EnumDescriptor*
AxesInfo_TrajState_descriptor();
template <typename T>
const std::string& AxesInfo_TrajState_Name(T value) {
  static_assert(std::is_same<T, AxesInfo_TrajState>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TrajState_Name().");
  return AxesInfo_TrajState_Name(static_cast<AxesInfo_TrajState>(value));
}
template <>
inline const std::string& AxesInfo_TrajState_Name(AxesInfo_TrajState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AxesInfo_TrajState_descriptor,
                                                 0, 9>(
      static_cast<int>(value));
}
inline bool AxesInfo_TrajState_Parse(absl::string_view name, AxesInfo_TrajState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AxesInfo_TrajState>(
      AxesInfo_TrajState_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class LinearTarget final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.LinearTarget) */ {
 public:
  inline LinearTarget() : LinearTarget(nullptr) {}
  ~LinearTarget() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR LinearTarget(::google::protobuf::internal::ConstantInitialized);

  LinearTarget(const LinearTarget& from);
  LinearTarget(LinearTarget&& from) noexcept
    : LinearTarget() {
    *this = ::std::move(from);
  }

  inline LinearTarget& operator=(const LinearTarget& from) {
    CopyFrom(from);
    return *this;
  }
  inline LinearTarget& operator=(LinearTarget&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LinearTarget& default_instance() {
    return *internal_default_instance();
  }
  static inline const LinearTarget* internal_default_instance() {
    return reinterpret_cast<const LinearTarget*>(
               &_LinearTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LinearTarget& a, LinearTarget& b) {
    a.Swap(&b);
  }
  inline void Swap(LinearTarget* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LinearTarget* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LinearTarget* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LinearTarget>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LinearTarget& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const LinearTarget& from) {
    LinearTarget::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LinearTarget* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.LinearTarget";
  }
  protected:
  explicit LinearTarget(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartMmFieldNumber = 1,
    kTargetMmFieldNumber = 2,
    kVelMmFieldNumber = 3,
    kAccMmFieldNumber = 4,
    kIsAbsoluteFieldNumber = 5,
    kTeachingModeFieldNumber = 10,
  };
  // repeated float start_mm = 1;
  int start_mm_size() const;
  private:
  int _internal_start_mm_size() const;

  public:
  void clear_start_mm() ;
  float start_mm(int index) const;
  void set_start_mm(int index, float value);
  void add_start_mm(float value);
  const ::google::protobuf::RepeatedField<float>& start_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_start_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_start_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_start_mm();

  public:
  // repeated float target_mm = 2;
  int target_mm_size() const;
  private:
  int _internal_target_mm_size() const;

  public:
  void clear_target_mm() ;
  float target_mm(int index) const;
  void set_target_mm(int index, float value);
  void add_target_mm(float value);
  const ::google::protobuf::RepeatedField<float>& target_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_target_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_target_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_target_mm();

  public:
  // float vel_mm = 3;
  void clear_vel_mm() ;
  float vel_mm() const;
  void set_vel_mm(float value);

  private:
  float _internal_vel_mm() const;
  void _internal_set_vel_mm(float value);

  public:
  // float acc_mm = 4;
  void clear_acc_mm() ;
  float acc_mm() const;
  void set_acc_mm(float value);

  private:
  float _internal_acc_mm() const;
  void _internal_set_acc_mm(float value);

  public:
  // bool is_absolute = 5;
  void clear_is_absolute() ;
  bool is_absolute() const;
  void set_is_absolute(bool value);

  private:
  bool _internal_is_absolute() const;
  void _internal_set_is_absolute(bool value);

  public:
  // bool teaching_mode = 10;
  void clear_teaching_mode() ;
  bool teaching_mode() const;
  void set_teaching_mode(bool value);

  private:
  bool _internal_teaching_mode() const;
  void _internal_set_teaching_mode(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.LinearTarget)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedField<float> start_mm_;
    ::google::protobuf::RepeatedField<float> target_mm_;
    float vel_mm_;
    float acc_mm_;
    bool is_absolute_;
    bool teaching_mode_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_linear_2eproto;
};// -------------------------------------------------------------------

class TargetTorque final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.TargetTorque) */ {
 public:
  inline TargetTorque() : TargetTorque(nullptr) {}
  ~TargetTorque() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR TargetTorque(::google::protobuf::internal::ConstantInitialized);

  TargetTorque(const TargetTorque& from);
  TargetTorque(TargetTorque&& from) noexcept
    : TargetTorque() {
    *this = ::std::move(from);
  }

  inline TargetTorque& operator=(const TargetTorque& from) {
    CopyFrom(from);
    return *this;
  }
  inline TargetTorque& operator=(TargetTorque&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TargetTorque& default_instance() {
    return *internal_default_instance();
  }
  static inline const TargetTorque* internal_default_instance() {
    return reinterpret_cast<const TargetTorque*>(
               &_TargetTorque_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TargetTorque& a, TargetTorque& b) {
    a.Swap(&b);
  }
  inline void Swap(TargetTorque* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TargetTorque* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TargetTorque* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TargetTorque>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TargetTorque& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const TargetTorque& from) {
    TargetTorque::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TargetTorque* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.TargetTorque";
  }
  protected:
  explicit TargetTorque(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetNmFieldNumber = 1,
  };
  // float target_nm = 1;
  void clear_target_nm() ;
  float target_nm() const;
  void set_target_nm(float value);

  private:
  float _internal_target_nm() const;
  void _internal_set_target_nm(float value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.TargetTorque)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float target_nm_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_linear_2eproto;
};// -------------------------------------------------------------------

class ControlGains final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.ControlGains) */ {
 public:
  inline ControlGains() : ControlGains(nullptr) {}
  ~ControlGains() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlGains(::google::protobuf::internal::ConstantInitialized);

  ControlGains(const ControlGains& from);
  ControlGains(ControlGains&& from) noexcept
    : ControlGains() {
    *this = ::std::move(from);
  }

  inline ControlGains& operator=(const ControlGains& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlGains& operator=(ControlGains&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlGains& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlGains* internal_default_instance() {
    return reinterpret_cast<const ControlGains*>(
               &_ControlGains_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ControlGains& a, ControlGains& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlGains* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlGains* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlGains* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlGains>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlGains& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlGains& from) {
    ControlGains::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlGains* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.ControlGains";
  }
  protected:
  explicit ControlGains(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexFieldNumber = 1,
    kKpFieldNumber = 2,
    kKvFieldNumber = 3,
    kKiFieldNumber = 4,
  };
  // uint32 index = 1;
  void clear_index() ;
  ::uint32_t index() const;
  void set_index(::uint32_t value);

  private:
  ::uint32_t _internal_index() const;
  void _internal_set_index(::uint32_t value);

  public:
  // float kp = 2;
  void clear_kp() ;
  float kp() const;
  void set_kp(float value);

  private:
  float _internal_kp() const;
  void _internal_set_kp(float value);

  public:
  // float kv = 3;
  void clear_kv() ;
  float kv() const;
  void set_kv(float value);

  private:
  float _internal_kv() const;
  void _internal_set_kv(float value);

  public:
  // float ki = 4;
  void clear_ki() ;
  float ki() const;
  void set_ki(float value);

  private:
  float _internal_ki() const;
  void _internal_set_ki(float value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.ControlGains)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t index_;
    float kp_;
    float kv_;
    float ki_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_linear_2eproto;
};// -------------------------------------------------------------------

class Index final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.Index) */ {
 public:
  inline Index() : Index(nullptr) {}
  ~Index() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Index(::google::protobuf::internal::ConstantInitialized);

  Index(const Index& from);
  Index(Index&& from) noexcept
    : Index() {
    *this = ::std::move(from);
  }

  inline Index& operator=(const Index& from) {
    CopyFrom(from);
    return *this;
  }
  inline Index& operator=(Index&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Index& default_instance() {
    return *internal_default_instance();
  }
  static inline const Index* internal_default_instance() {
    return reinterpret_cast<const Index*>(
               &_Index_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Index& a, Index& b) {
    a.Swap(&b);
  }
  inline void Swap(Index* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Index* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Index* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Index>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Index& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Index& from) {
    Index::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Index* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.Index";
  }
  protected:
  explicit Index(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexFieldNumber = 1,
  };
  // uint32 index = 1;
  void clear_index() ;
  ::uint32_t index() const;
  void set_index(::uint32_t value);

  private:
  ::uint32_t _internal_index() const;
  void _internal_set_index(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.Index)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t index_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_linear_2eproto;
};// -------------------------------------------------------------------

class LinearAxisServoData final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.LinearAxisServoData) */ {
 public:
  inline LinearAxisServoData() : LinearAxisServoData(nullptr) {}
  ~LinearAxisServoData() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR LinearAxisServoData(::google::protobuf::internal::ConstantInitialized);

  LinearAxisServoData(const LinearAxisServoData& from);
  LinearAxisServoData(LinearAxisServoData&& from) noexcept
    : LinearAxisServoData() {
    *this = ::std::move(from);
  }

  inline LinearAxisServoData& operator=(const LinearAxisServoData& from) {
    CopyFrom(from);
    return *this;
  }
  inline LinearAxisServoData& operator=(LinearAxisServoData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LinearAxisServoData& default_instance() {
    return *internal_default_instance();
  }
  static inline const LinearAxisServoData* internal_default_instance() {
    return reinterpret_cast<const LinearAxisServoData*>(
               &_LinearAxisServoData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LinearAxisServoData& a, LinearAxisServoData& b) {
    a.Swap(&b);
  }
  inline void Swap(LinearAxisServoData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LinearAxisServoData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LinearAxisServoData* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LinearAxisServoData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LinearAxisServoData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const LinearAxisServoData& from) {
    LinearAxisServoData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LinearAxisServoData* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.LinearAxisServoData";
  }
  protected:
  explicit LinearAxisServoData(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexFieldNumber = 1,
    kZeroPosFieldNumber = 2,
  };
  // uint32 index = 1;
  void clear_index() ;
  ::uint32_t index() const;
  void set_index(::uint32_t value);

  private:
  ::uint32_t _internal_index() const;
  void _internal_set_index(::uint32_t value);

  public:
  // float zero_pos = 2;
  void clear_zero_pos() ;
  float zero_pos() const;
  void set_zero_pos(float value);

  private:
  float _internal_zero_pos() const;
  void _internal_set_zero_pos(float value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.LinearAxisServoData)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t index_;
    float zero_pos_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_linear_2eproto;
};// -------------------------------------------------------------------

class AxesInfo final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Nrmk.IndyFramework.AxesInfo) */ {
 public:
  inline AxesInfo() : AxesInfo(nullptr) {}
  ~AxesInfo() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AxesInfo(::google::protobuf::internal::ConstantInitialized);

  AxesInfo(const AxesInfo& from);
  AxesInfo(AxesInfo&& from) noexcept
    : AxesInfo() {
    *this = ::std::move(from);
  }

  inline AxesInfo& operator=(const AxesInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline AxesInfo& operator=(AxesInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AxesInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const AxesInfo* internal_default_instance() {
    return reinterpret_cast<const AxesInfo*>(
               &_AxesInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AxesInfo& a, AxesInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(AxesInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AxesInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AxesInfo* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AxesInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AxesInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AxesInfo& from) {
    AxesInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AxesInfo* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Nrmk.IndyFramework.AxesInfo";
  }
  protected:
  explicit AxesInfo(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using OpState = AxesInfo_OpState;
  static constexpr OpState SYSTEM_OFF = AxesInfo_OpState_SYSTEM_OFF;
  static constexpr OpState SYSTEM_ON = AxesInfo_OpState_SYSTEM_ON;
  static constexpr OpState VIOLATE = AxesInfo_OpState_VIOLATE;
  static constexpr OpState RECOVER_HARD = AxesInfo_OpState_RECOVER_HARD;
  static constexpr OpState RECOVER_SOFT = AxesInfo_OpState_RECOVER_SOFT;
  static constexpr OpState IDLE = AxesInfo_OpState_IDLE;
  static constexpr OpState MOVING = AxesInfo_OpState_MOVING;
  static constexpr OpState PAUSING = AxesInfo_OpState_PAUSING;
  static constexpr OpState COLLISION_PAUSE = AxesInfo_OpState_COLLISION_PAUSE;
  static constexpr OpState COLLISION_STOP = AxesInfo_OpState_COLLISION_STOP;
  static inline bool OpState_IsValid(int value) {
    return AxesInfo_OpState_IsValid(value);
  }
  static constexpr OpState OpState_MIN = AxesInfo_OpState_OpState_MIN;
  static constexpr OpState OpState_MAX = AxesInfo_OpState_OpState_MAX;
  static constexpr int OpState_ARRAYSIZE = AxesInfo_OpState_OpState_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* OpState_descriptor() {
    return AxesInfo_OpState_descriptor();
  }
  template <typename T>
  static inline const std::string& OpState_Name(T value) {
    return AxesInfo_OpState_Name(value);
  }
  static inline bool OpState_Parse(absl::string_view name, OpState* value) {
    return AxesInfo_OpState_Parse(name, value);
  }

  using TrajState = AxesInfo_TrajState;
  static constexpr TrajState TRAJ_NONE = AxesInfo_TrajState_TRAJ_NONE;
  static constexpr TrajState TRAJ_INIT = AxesInfo_TrajState_TRAJ_INIT;
  static constexpr TrajState TRAJ_CALC = AxesInfo_TrajState_TRAJ_CALC;
  static constexpr TrajState TRAJ_STBY = AxesInfo_TrajState_TRAJ_STBY;
  static constexpr TrajState TRAJ_ACC = AxesInfo_TrajState_TRAJ_ACC;
  static constexpr TrajState TRAJ_CRZ = AxesInfo_TrajState_TRAJ_CRZ;
  static constexpr TrajState TRAJ_DEC = AxesInfo_TrajState_TRAJ_DEC;
  static constexpr TrajState TRAJ_CANC = AxesInfo_TrajState_TRAJ_CANC;
  static constexpr TrajState TRAJ_FIN = AxesInfo_TrajState_TRAJ_FIN;
  static constexpr TrajState TRAJ_ERR = AxesInfo_TrajState_TRAJ_ERR;
  static inline bool TrajState_IsValid(int value) {
    return AxesInfo_TrajState_IsValid(value);
  }
  static constexpr TrajState TrajState_MIN = AxesInfo_TrajState_TrajState_MIN;
  static constexpr TrajState TrajState_MAX = AxesInfo_TrajState_TrajState_MAX;
  static constexpr int TrajState_ARRAYSIZE = AxesInfo_TrajState_TrajState_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* TrajState_descriptor() {
    return AxesInfo_TrajState_descriptor();
  }
  template <typename T>
  static inline const std::string& TrajState_Name(T value) {
    return AxesInfo_TrajState_Name(value);
  }
  static inline bool TrajState_Parse(absl::string_view name, TrajState* value) {
    return AxesInfo_TrajState_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kActiveFieldNumber = 1,
    kPosMmFieldNumber = 2,
    kVelMmFieldNumber = 3,
    kDesposMmFieldNumber = 4,
    kDesvelMmFieldNumber = 5,
    kDesaccMmFieldNumber = 6,
    kAxisTypeFieldNumber = 16,
    kNumAxesFieldNumber = 10,
    kOpStateFieldNumber = 11,
    kTrajStateFieldNumber = 12,
    kRecoverTimeFieldNumber = 13,
    kIsTargetReachedFieldNumber = 20,
  };
  // repeated bool active = 1;
  int active_size() const;
  private:
  int _internal_active_size() const;

  public:
  void clear_active() ;
  bool active(int index) const;
  void set_active(int index, bool value);
  void add_active(bool value);
  const ::google::protobuf::RepeatedField<bool>& active() const;
  ::google::protobuf::RepeatedField<bool>* mutable_active();

  private:
  const ::google::protobuf::RepeatedField<bool>& _internal_active() const;
  ::google::protobuf::RepeatedField<bool>* _internal_mutable_active();

  public:
  // repeated float pos_mm = 2;
  int pos_mm_size() const;
  private:
  int _internal_pos_mm_size() const;

  public:
  void clear_pos_mm() ;
  float pos_mm(int index) const;
  void set_pos_mm(int index, float value);
  void add_pos_mm(float value);
  const ::google::protobuf::RepeatedField<float>& pos_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_pos_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_pos_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_pos_mm();

  public:
  // repeated float vel_mm = 3;
  int vel_mm_size() const;
  private:
  int _internal_vel_mm_size() const;

  public:
  void clear_vel_mm() ;
  float vel_mm(int index) const;
  void set_vel_mm(int index, float value);
  void add_vel_mm(float value);
  const ::google::protobuf::RepeatedField<float>& vel_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_vel_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_vel_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_vel_mm();

  public:
  // repeated float despos_mm = 4;
  int despos_mm_size() const;
  private:
  int _internal_despos_mm_size() const;

  public:
  void clear_despos_mm() ;
  float despos_mm(int index) const;
  void set_despos_mm(int index, float value);
  void add_despos_mm(float value);
  const ::google::protobuf::RepeatedField<float>& despos_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_despos_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_despos_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_despos_mm();

  public:
  // repeated float desvel_mm = 5;
  int desvel_mm_size() const;
  private:
  int _internal_desvel_mm_size() const;

  public:
  void clear_desvel_mm() ;
  float desvel_mm(int index) const;
  void set_desvel_mm(int index, float value);
  void add_desvel_mm(float value);
  const ::google::protobuf::RepeatedField<float>& desvel_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_desvel_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_desvel_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_desvel_mm();

  public:
  // repeated float desacc_mm = 6;
  int desacc_mm_size() const;
  private:
  int _internal_desacc_mm_size() const;

  public:
  void clear_desacc_mm() ;
  float desacc_mm(int index) const;
  void set_desacc_mm(int index, float value);
  void add_desacc_mm(float value);
  const ::google::protobuf::RepeatedField<float>& desacc_mm() const;
  ::google::protobuf::RepeatedField<float>* mutable_desacc_mm();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_desacc_mm() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_desacc_mm();

  public:
  // repeated .Nrmk.IndyFramework.AxisType axis_type = 16;
  int axis_type_size() const;
  private:
  int _internal_axis_type_size() const;

  public:
  void clear_axis_type() ;
  public:
  ::Nrmk::IndyFramework::AxisType axis_type(int index) const;
  void set_axis_type(int index, ::Nrmk::IndyFramework::AxisType value);
  void add_axis_type(::Nrmk::IndyFramework::AxisType value);
  const ::google::protobuf::RepeatedField<int>& axis_type() const;
  ::google::protobuf::RepeatedField<int>* mutable_axis_type();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_axis_type() const;
  ::google::protobuf::RepeatedField<int>* _internal_mutable_axis_type();

  public:
  // uint32 num_axes = 10;
  void clear_num_axes() ;
  ::uint32_t num_axes() const;
  void set_num_axes(::uint32_t value);

  private:
  ::uint32_t _internal_num_axes() const;
  void _internal_set_num_axes(::uint32_t value);

  public:
  // .Nrmk.IndyFramework.AxesInfo.OpState op_state = 11;
  void clear_op_state() ;
  ::Nrmk::IndyFramework::AxesInfo_OpState op_state() const;
  void set_op_state(::Nrmk::IndyFramework::AxesInfo_OpState value);

  private:
  ::Nrmk::IndyFramework::AxesInfo_OpState _internal_op_state() const;
  void _internal_set_op_state(::Nrmk::IndyFramework::AxesInfo_OpState value);

  public:
  // .Nrmk.IndyFramework.AxesInfo.TrajState traj_state = 12;
  void clear_traj_state() ;
  ::Nrmk::IndyFramework::AxesInfo_TrajState traj_state() const;
  void set_traj_state(::Nrmk::IndyFramework::AxesInfo_TrajState value);

  private:
  ::Nrmk::IndyFramework::AxesInfo_TrajState _internal_traj_state() const;
  void _internal_set_traj_state(::Nrmk::IndyFramework::AxesInfo_TrajState value);

  public:
  // float recover_time = 13;
  void clear_recover_time() ;
  float recover_time() const;
  void set_recover_time(float value);

  private:
  float _internal_recover_time() const;
  void _internal_set_recover_time(float value);

  public:
  // bool is_target_reached = 20;
  void clear_is_target_reached() ;
  bool is_target_reached() const;
  void set_is_target_reached(bool value);

  private:
  bool _internal_is_target_reached() const;
  void _internal_set_is_target_reached(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Nrmk.IndyFramework.AxesInfo)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 12, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedField<bool> active_;
    ::google::protobuf::RepeatedField<float> pos_mm_;
    ::google::protobuf::RepeatedField<float> vel_mm_;
    ::google::protobuf::RepeatedField<float> despos_mm_;
    ::google::protobuf::RepeatedField<float> desvel_mm_;
    ::google::protobuf::RepeatedField<float> desacc_mm_;
    ::google::protobuf::RepeatedField<int> axis_type_;
    mutable ::google::protobuf::internal::CachedSize _axis_type_cached_byte_size_;
    ::uint32_t num_axes_;
    int op_state_;
    int traj_state_;
    float recover_time_;
    bool is_target_reached_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_linear_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LinearTarget

// repeated float start_mm = 1;
inline int LinearTarget::_internal_start_mm_size() const {
  return _internal_start_mm().size();
}
inline int LinearTarget::start_mm_size() const {
  return _internal_start_mm_size();
}
inline void LinearTarget::clear_start_mm() {
  _internal_mutable_start_mm()->Clear();
}
inline float LinearTarget::start_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearTarget.start_mm)
  return _internal_start_mm().Get(index);
}
inline void LinearTarget::set_start_mm(int index, float value) {
  _internal_mutable_start_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearTarget.start_mm)
}
inline void LinearTarget::add_start_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_start_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.LinearTarget.start_mm)
}
inline const ::google::protobuf::RepeatedField<float>& LinearTarget::start_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.LinearTarget.start_mm)
  return _internal_start_mm();
}
inline ::google::protobuf::RepeatedField<float>* LinearTarget::mutable_start_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.LinearTarget.start_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_start_mm();
}

inline const ::google::protobuf::RepeatedField<float>& LinearTarget::_internal_start_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.start_mm_;
}
inline ::google::protobuf::RepeatedField<float>* LinearTarget::_internal_mutable_start_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.start_mm_;
}

// repeated float target_mm = 2;
inline int LinearTarget::_internal_target_mm_size() const {
  return _internal_target_mm().size();
}
inline int LinearTarget::target_mm_size() const {
  return _internal_target_mm_size();
}
inline void LinearTarget::clear_target_mm() {
  _internal_mutable_target_mm()->Clear();
}
inline float LinearTarget::target_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearTarget.target_mm)
  return _internal_target_mm().Get(index);
}
inline void LinearTarget::set_target_mm(int index, float value) {
  _internal_mutable_target_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearTarget.target_mm)
}
inline void LinearTarget::add_target_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_target_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.LinearTarget.target_mm)
}
inline const ::google::protobuf::RepeatedField<float>& LinearTarget::target_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.LinearTarget.target_mm)
  return _internal_target_mm();
}
inline ::google::protobuf::RepeatedField<float>* LinearTarget::mutable_target_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.LinearTarget.target_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_target_mm();
}

inline const ::google::protobuf::RepeatedField<float>& LinearTarget::_internal_target_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.target_mm_;
}
inline ::google::protobuf::RepeatedField<float>* LinearTarget::_internal_mutable_target_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.target_mm_;
}

// float vel_mm = 3;
inline void LinearTarget::clear_vel_mm() {
  _impl_.vel_mm_ = 0;
}
inline float LinearTarget::vel_mm() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearTarget.vel_mm)
  return _internal_vel_mm();
}
inline void LinearTarget::set_vel_mm(float value) {
  _internal_set_vel_mm(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearTarget.vel_mm)
}
inline float LinearTarget::_internal_vel_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.vel_mm_;
}
inline void LinearTarget::_internal_set_vel_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.vel_mm_ = value;
}

// float acc_mm = 4;
inline void LinearTarget::clear_acc_mm() {
  _impl_.acc_mm_ = 0;
}
inline float LinearTarget::acc_mm() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearTarget.acc_mm)
  return _internal_acc_mm();
}
inline void LinearTarget::set_acc_mm(float value) {
  _internal_set_acc_mm(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearTarget.acc_mm)
}
inline float LinearTarget::_internal_acc_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.acc_mm_;
}
inline void LinearTarget::_internal_set_acc_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.acc_mm_ = value;
}

// bool is_absolute = 5;
inline void LinearTarget::clear_is_absolute() {
  _impl_.is_absolute_ = false;
}
inline bool LinearTarget::is_absolute() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearTarget.is_absolute)
  return _internal_is_absolute();
}
inline void LinearTarget::set_is_absolute(bool value) {
  _internal_set_is_absolute(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearTarget.is_absolute)
}
inline bool LinearTarget::_internal_is_absolute() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.is_absolute_;
}
inline void LinearTarget::_internal_set_is_absolute(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.is_absolute_ = value;
}

// bool teaching_mode = 10;
inline void LinearTarget::clear_teaching_mode() {
  _impl_.teaching_mode_ = false;
}
inline bool LinearTarget::teaching_mode() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearTarget.teaching_mode)
  return _internal_teaching_mode();
}
inline void LinearTarget::set_teaching_mode(bool value) {
  _internal_set_teaching_mode(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearTarget.teaching_mode)
}
inline bool LinearTarget::_internal_teaching_mode() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.teaching_mode_;
}
inline void LinearTarget::_internal_set_teaching_mode(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.teaching_mode_ = value;
}

// -------------------------------------------------------------------

// TargetTorque

// float target_nm = 1;
inline void TargetTorque::clear_target_nm() {
  _impl_.target_nm_ = 0;
}
inline float TargetTorque::target_nm() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.TargetTorque.target_nm)
  return _internal_target_nm();
}
inline void TargetTorque::set_target_nm(float value) {
  _internal_set_target_nm(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.TargetTorque.target_nm)
}
inline float TargetTorque::_internal_target_nm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.target_nm_;
}
inline void TargetTorque::_internal_set_target_nm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.target_nm_ = value;
}

// -------------------------------------------------------------------

// ControlGains

// uint32 index = 1;
inline void ControlGains::clear_index() {
  _impl_.index_ = 0u;
}
inline ::uint32_t ControlGains::index() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.ControlGains.index)
  return _internal_index();
}
inline void ControlGains::set_index(::uint32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.ControlGains.index)
}
inline ::uint32_t ControlGains::_internal_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.index_;
}
inline void ControlGains::_internal_set_index(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.index_ = value;
}

// float kp = 2;
inline void ControlGains::clear_kp() {
  _impl_.kp_ = 0;
}
inline float ControlGains::kp() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.ControlGains.kp)
  return _internal_kp();
}
inline void ControlGains::set_kp(float value) {
  _internal_set_kp(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.ControlGains.kp)
}
inline float ControlGains::_internal_kp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.kp_;
}
inline void ControlGains::_internal_set_kp(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.kp_ = value;
}

// float kv = 3;
inline void ControlGains::clear_kv() {
  _impl_.kv_ = 0;
}
inline float ControlGains::kv() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.ControlGains.kv)
  return _internal_kv();
}
inline void ControlGains::set_kv(float value) {
  _internal_set_kv(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.ControlGains.kv)
}
inline float ControlGains::_internal_kv() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.kv_;
}
inline void ControlGains::_internal_set_kv(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.kv_ = value;
}

// float ki = 4;
inline void ControlGains::clear_ki() {
  _impl_.ki_ = 0;
}
inline float ControlGains::ki() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.ControlGains.ki)
  return _internal_ki();
}
inline void ControlGains::set_ki(float value) {
  _internal_set_ki(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.ControlGains.ki)
}
inline float ControlGains::_internal_ki() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.ki_;
}
inline void ControlGains::_internal_set_ki(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.ki_ = value;
}

// -------------------------------------------------------------------

// Index

// uint32 index = 1;
inline void Index::clear_index() {
  _impl_.index_ = 0u;
}
inline ::uint32_t Index::index() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.Index.index)
  return _internal_index();
}
inline void Index::set_index(::uint32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.Index.index)
}
inline ::uint32_t Index::_internal_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.index_;
}
inline void Index::_internal_set_index(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.index_ = value;
}

// -------------------------------------------------------------------

// LinearAxisServoData

// uint32 index = 1;
inline void LinearAxisServoData::clear_index() {
  _impl_.index_ = 0u;
}
inline ::uint32_t LinearAxisServoData::index() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearAxisServoData.index)
  return _internal_index();
}
inline void LinearAxisServoData::set_index(::uint32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearAxisServoData.index)
}
inline ::uint32_t LinearAxisServoData::_internal_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.index_;
}
inline void LinearAxisServoData::_internal_set_index(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.index_ = value;
}

// float zero_pos = 2;
inline void LinearAxisServoData::clear_zero_pos() {
  _impl_.zero_pos_ = 0;
}
inline float LinearAxisServoData::zero_pos() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.LinearAxisServoData.zero_pos)
  return _internal_zero_pos();
}
inline void LinearAxisServoData::set_zero_pos(float value) {
  _internal_set_zero_pos(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.LinearAxisServoData.zero_pos)
}
inline float LinearAxisServoData::_internal_zero_pos() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.zero_pos_;
}
inline void LinearAxisServoData::_internal_set_zero_pos(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.zero_pos_ = value;
}

// -------------------------------------------------------------------

// AxesInfo

// repeated bool active = 1;
inline int AxesInfo::_internal_active_size() const {
  return _internal_active().size();
}
inline int AxesInfo::active_size() const {
  return _internal_active_size();
}
inline void AxesInfo::clear_active() {
  _internal_mutable_active()->Clear();
}
inline bool AxesInfo::active(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.active)
  return _internal_active().Get(index);
}
inline void AxesInfo::set_active(int index, bool value) {
  _internal_mutable_active()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.active)
}
inline void AxesInfo::add_active(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_active()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.active)
}
inline const ::google::protobuf::RepeatedField<bool>& AxesInfo::active() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.active)
  return _internal_active();
}
inline ::google::protobuf::RepeatedField<bool>* AxesInfo::mutable_active() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.active)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_active();
}

inline const ::google::protobuf::RepeatedField<bool>& AxesInfo::_internal_active() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.active_;
}
inline ::google::protobuf::RepeatedField<bool>* AxesInfo::_internal_mutable_active() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.active_;
}

// repeated float pos_mm = 2;
inline int AxesInfo::_internal_pos_mm_size() const {
  return _internal_pos_mm().size();
}
inline int AxesInfo::pos_mm_size() const {
  return _internal_pos_mm_size();
}
inline void AxesInfo::clear_pos_mm() {
  _internal_mutable_pos_mm()->Clear();
}
inline float AxesInfo::pos_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.pos_mm)
  return _internal_pos_mm().Get(index);
}
inline void AxesInfo::set_pos_mm(int index, float value) {
  _internal_mutable_pos_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.pos_mm)
}
inline void AxesInfo::add_pos_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_pos_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.pos_mm)
}
inline const ::google::protobuf::RepeatedField<float>& AxesInfo::pos_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.pos_mm)
  return _internal_pos_mm();
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::mutable_pos_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.pos_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_pos_mm();
}

inline const ::google::protobuf::RepeatedField<float>& AxesInfo::_internal_pos_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.pos_mm_;
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::_internal_mutable_pos_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.pos_mm_;
}

// repeated float vel_mm = 3;
inline int AxesInfo::_internal_vel_mm_size() const {
  return _internal_vel_mm().size();
}
inline int AxesInfo::vel_mm_size() const {
  return _internal_vel_mm_size();
}
inline void AxesInfo::clear_vel_mm() {
  _internal_mutable_vel_mm()->Clear();
}
inline float AxesInfo::vel_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.vel_mm)
  return _internal_vel_mm().Get(index);
}
inline void AxesInfo::set_vel_mm(int index, float value) {
  _internal_mutable_vel_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.vel_mm)
}
inline void AxesInfo::add_vel_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_vel_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.vel_mm)
}
inline const ::google::protobuf::RepeatedField<float>& AxesInfo::vel_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.vel_mm)
  return _internal_vel_mm();
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::mutable_vel_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.vel_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_vel_mm();
}

inline const ::google::protobuf::RepeatedField<float>& AxesInfo::_internal_vel_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.vel_mm_;
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::_internal_mutable_vel_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.vel_mm_;
}

// repeated float despos_mm = 4;
inline int AxesInfo::_internal_despos_mm_size() const {
  return _internal_despos_mm().size();
}
inline int AxesInfo::despos_mm_size() const {
  return _internal_despos_mm_size();
}
inline void AxesInfo::clear_despos_mm() {
  _internal_mutable_despos_mm()->Clear();
}
inline float AxesInfo::despos_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.despos_mm)
  return _internal_despos_mm().Get(index);
}
inline void AxesInfo::set_despos_mm(int index, float value) {
  _internal_mutable_despos_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.despos_mm)
}
inline void AxesInfo::add_despos_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_despos_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.despos_mm)
}
inline const ::google::protobuf::RepeatedField<float>& AxesInfo::despos_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.despos_mm)
  return _internal_despos_mm();
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::mutable_despos_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.despos_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_despos_mm();
}

inline const ::google::protobuf::RepeatedField<float>& AxesInfo::_internal_despos_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.despos_mm_;
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::_internal_mutable_despos_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.despos_mm_;
}

// repeated float desvel_mm = 5;
inline int AxesInfo::_internal_desvel_mm_size() const {
  return _internal_desvel_mm().size();
}
inline int AxesInfo::desvel_mm_size() const {
  return _internal_desvel_mm_size();
}
inline void AxesInfo::clear_desvel_mm() {
  _internal_mutable_desvel_mm()->Clear();
}
inline float AxesInfo::desvel_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.desvel_mm)
  return _internal_desvel_mm().Get(index);
}
inline void AxesInfo::set_desvel_mm(int index, float value) {
  _internal_mutable_desvel_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.desvel_mm)
}
inline void AxesInfo::add_desvel_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_desvel_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.desvel_mm)
}
inline const ::google::protobuf::RepeatedField<float>& AxesInfo::desvel_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.desvel_mm)
  return _internal_desvel_mm();
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::mutable_desvel_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.desvel_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_desvel_mm();
}

inline const ::google::protobuf::RepeatedField<float>& AxesInfo::_internal_desvel_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.desvel_mm_;
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::_internal_mutable_desvel_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.desvel_mm_;
}

// repeated float desacc_mm = 6;
inline int AxesInfo::_internal_desacc_mm_size() const {
  return _internal_desacc_mm().size();
}
inline int AxesInfo::desacc_mm_size() const {
  return _internal_desacc_mm_size();
}
inline void AxesInfo::clear_desacc_mm() {
  _internal_mutable_desacc_mm()->Clear();
}
inline float AxesInfo::desacc_mm(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.desacc_mm)
  return _internal_desacc_mm().Get(index);
}
inline void AxesInfo::set_desacc_mm(int index, float value) {
  _internal_mutable_desacc_mm()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.desacc_mm)
}
inline void AxesInfo::add_desacc_mm(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_desacc_mm()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.desacc_mm)
}
inline const ::google::protobuf::RepeatedField<float>& AxesInfo::desacc_mm() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.desacc_mm)
  return _internal_desacc_mm();
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::mutable_desacc_mm() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.desacc_mm)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_desacc_mm();
}

inline const ::google::protobuf::RepeatedField<float>& AxesInfo::_internal_desacc_mm() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.desacc_mm_;
}
inline ::google::protobuf::RepeatedField<float>* AxesInfo::_internal_mutable_desacc_mm() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.desacc_mm_;
}

// uint32 num_axes = 10;
inline void AxesInfo::clear_num_axes() {
  _impl_.num_axes_ = 0u;
}
inline ::uint32_t AxesInfo::num_axes() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.num_axes)
  return _internal_num_axes();
}
inline void AxesInfo::set_num_axes(::uint32_t value) {
  _internal_set_num_axes(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.num_axes)
}
inline ::uint32_t AxesInfo::_internal_num_axes() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.num_axes_;
}
inline void AxesInfo::_internal_set_num_axes(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.num_axes_ = value;
}

// .Nrmk.IndyFramework.AxesInfo.OpState op_state = 11;
inline void AxesInfo::clear_op_state() {
  _impl_.op_state_ = 0;
}
inline ::Nrmk::IndyFramework::AxesInfo_OpState AxesInfo::op_state() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.op_state)
  return _internal_op_state();
}
inline void AxesInfo::set_op_state(::Nrmk::IndyFramework::AxesInfo_OpState value) {
  _internal_set_op_state(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.op_state)
}
inline ::Nrmk::IndyFramework::AxesInfo_OpState AxesInfo::_internal_op_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::Nrmk::IndyFramework::AxesInfo_OpState>(_impl_.op_state_);
}
inline void AxesInfo::_internal_set_op_state(::Nrmk::IndyFramework::AxesInfo_OpState value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.op_state_ = value;
}

// .Nrmk.IndyFramework.AxesInfo.TrajState traj_state = 12;
inline void AxesInfo::clear_traj_state() {
  _impl_.traj_state_ = 0;
}
inline ::Nrmk::IndyFramework::AxesInfo_TrajState AxesInfo::traj_state() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.traj_state)
  return _internal_traj_state();
}
inline void AxesInfo::set_traj_state(::Nrmk::IndyFramework::AxesInfo_TrajState value) {
  _internal_set_traj_state(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.traj_state)
}
inline ::Nrmk::IndyFramework::AxesInfo_TrajState AxesInfo::_internal_traj_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::Nrmk::IndyFramework::AxesInfo_TrajState>(_impl_.traj_state_);
}
inline void AxesInfo::_internal_set_traj_state(::Nrmk::IndyFramework::AxesInfo_TrajState value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.traj_state_ = value;
}

// float recover_time = 13;
inline void AxesInfo::clear_recover_time() {
  _impl_.recover_time_ = 0;
}
inline float AxesInfo::recover_time() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.recover_time)
  return _internal_recover_time();
}
inline void AxesInfo::set_recover_time(float value) {
  _internal_set_recover_time(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.recover_time)
}
inline float AxesInfo::_internal_recover_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.recover_time_;
}
inline void AxesInfo::_internal_set_recover_time(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.recover_time_ = value;
}

// repeated .Nrmk.IndyFramework.AxisType axis_type = 16;
inline int AxesInfo::_internal_axis_type_size() const {
  return _internal_axis_type().size();
}
inline int AxesInfo::axis_type_size() const {
  return _internal_axis_type_size();
}
inline void AxesInfo::clear_axis_type() {
  _internal_mutable_axis_type()->Clear();
}
inline ::Nrmk::IndyFramework::AxisType AxesInfo::axis_type(int index) const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.axis_type)
  return static_cast<::Nrmk::IndyFramework::AxisType>(_internal_axis_type().Get(index));
}
inline void AxesInfo::set_axis_type(int index, ::Nrmk::IndyFramework::AxisType value) {
  _internal_mutable_axis_type()->Set(index, value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.axis_type)
}
inline void AxesInfo::add_axis_type(::Nrmk::IndyFramework::AxisType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_axis_type()->Add(value);
  // @@protoc_insertion_point(field_add:Nrmk.IndyFramework.AxesInfo.axis_type)
}
inline const ::google::protobuf::RepeatedField<int>& AxesInfo::axis_type() const {
  // @@protoc_insertion_point(field_list:Nrmk.IndyFramework.AxesInfo.axis_type)
  return _internal_axis_type();
}
inline ::google::protobuf::RepeatedField<int>* AxesInfo::mutable_axis_type() {
  // @@protoc_insertion_point(field_mutable_list:Nrmk.IndyFramework.AxesInfo.axis_type)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_axis_type();
}
inline const ::google::protobuf::RepeatedField<int>& AxesInfo::_internal_axis_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.axis_type_;
}
inline ::google::protobuf::RepeatedField<int>* AxesInfo::_internal_mutable_axis_type() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.axis_type_;
}

// bool is_target_reached = 20;
inline void AxesInfo::clear_is_target_reached() {
  _impl_.is_target_reached_ = false;
}
inline bool AxesInfo::is_target_reached() const {
  // @@protoc_insertion_point(field_get:Nrmk.IndyFramework.AxesInfo.is_target_reached)
  return _internal_is_target_reached();
}
inline void AxesInfo::set_is_target_reached(bool value) {
  _internal_set_is_target_reached(value);
  // @@protoc_insertion_point(field_set:Nrmk.IndyFramework.AxesInfo.is_target_reached)
}
inline bool AxesInfo::_internal_is_target_reached() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.is_target_reached_;
}
inline void AxesInfo::_internal_set_is_target_reached(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.is_target_reached_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Nrmk::IndyFramework::AxesInfo_OpState> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Nrmk::IndyFramework::AxesInfo_OpState>() {
  return ::Nrmk::IndyFramework::AxesInfo_OpState_descriptor();
}
template <>
struct is_proto_enum<::Nrmk::IndyFramework::AxesInfo_TrajState> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Nrmk::IndyFramework::AxesInfo_TrajState>() {
  return ::Nrmk::IndyFramework::AxesInfo_TrajState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_linear_2eproto_2epb_2eh
