// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moby.proto

#include "moby.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_moby_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_moby_2eproto = nullptr;
const ::uint32_t TableStruct_moby_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_moby_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nmoby.proto\022\022Nrmk.IndyFramework\032\017moby_m"
    "sgs.proto\032\021common_msgs.proto2\345\026\n\004Moby\022J\n"
    "\014GetMobyState\022\031.Nrmk.IndyFramework.Empty"
    "\032\035.Nrmk.IndyFramework.MobyState\"\000\022T\n\021Get"
    "MobyErrorState\022\031.Nrmk.IndyFramework.Empt"
    "y\032\".Nrmk.IndyFramework.MobyErrorState\"\000\022"
    "A\n\007Recover\022\031.Nrmk.IndyFramework.Empty\032\031."
    "Nrmk.IndyFramework.Empty\"\000\022H\n\013GetMobyPos"
    "e\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.Indy"
    "Framework.MobyPose\"\000\022F\n\nGetMobyVel\022\031.Nrm"
    "k.IndyFramework.Empty\032\033.Nrmk.IndyFramewo"
    "rk.MobyVel\"\000\022G\n\rResetMobyPose\022\031.Nrmk.Ind"
    "yFramework.Empty\032\031.Nrmk.IndyFramework.Em"
    "pty\"\000\022U\n\023GetRotationAngleDeg\022\031.Nrmk.Indy"
    "Framework.Empty\032!.Nrmk.IndyFramework.Swe"
    "rveDoubles\"\000\022O\n\rGetDriveSpeed\022\031.Nrmk.Ind"
    "yFramework.Empty\032!.Nrmk.IndyFramework.Sw"
    "erveDoubles\"\000\022J\n\014GetTargetVel\022\031.Nrmk.Ind"
    "yFramework.Empty\032\035.Nrmk.IndyFramework.Ta"
    "rgetVel\"\000\022R\n\024GetRotationZeroCount\022\031.Nrmk"
    ".IndyFramework.Empty\032\035.Nrmk.IndyFramewor"
    "k.ZeroCount\"\000\022J\n\013GetGyroData\022\031.Nrmk.Indy"
    "Framework.Empty\032\036.Nrmk.IndyFramework.Dou"
    "bleVals\"\000\022I\n\017ResetGyroSensor\022\031.Nrmk.Indy"
    "Framework.Empty\032\031.Nrmk.IndyFramework.Emp"
    "ty\"\000\022J\n\016UseGyroForOdom\022\033.Nrmk.IndyFramew"
    "ork.BoolVal\032\031.Nrmk.IndyFramework.Empty\"\000"
    "\022K\n\017GetGyroFullData\022\031.Nrmk.IndyFramework"
    ".Empty\032\033.Nrmk.IndyFramework.IMUData\"\000\022J\n"
    "\017GetIRSensorData\022\031.Nrmk.IndyFramework.Em"
    "pty\032\032.Nrmk.IndyFramework.IRData\"\000\022J\n\017Get"
    "USSensorData\022\031.Nrmk.IndyFramework.Empty\032"
    "\032.Nrmk.IndyFramework.USData\"\000\022F\n\nGetBMSD"
    "ata\022\031.Nrmk.IndyFramework.Empty\032\033.Nrmk.In"
    "dyFramework.BMSData\"\000\022L\n\016SetStepControl\022"
    "\035.Nrmk.IndyFramework.TargetVel\032\031.Nrmk.In"
    "dyFramework.Empty\"\000\022D\n\nStopMotion\022\031.Nrmk"
    ".IndyFramework.Empty\032\031.Nrmk.IndyFramewor"
    "k.Empty\"\000\022U\n\023SetRotationAngleDeg\022!.Nrmk."
    "IndyFramework.SwerveDoubles\032\031.Nrmk.IndyF"
    "ramework.Empty\"\000\022L\n\nDriveWheel\022!.Nrmk.In"
    "dyFramework.SwerveDoubles\032\031.Nrmk.IndyFra"
    "mework.Empty\"\000\022P\n\026SetZeroPosAsCurrentPos"
    "\022\031.Nrmk.IndyFramework.Empty\032\031.Nrmk.IndyF"
    "ramework.Empty\"\000\022P\n\021SetRotationVelAcc\022\036."
    "Nrmk.IndyFramework.DoubleVals\032\031.Nrmk.Ind"
    "yFramework.Empty\"\000\022R\n\027SetRotationInterpo"
    "lator\022\032.Nrmk.IndyFramework.IntVal\032\031.Nrmk"
    ".IndyFramework.Empty\"\000\022M\n\016SetDriveAccDec"
    "\022\036.Nrmk.IndyFramework.DoubleVals\032\031.Nrmk."
    "IndyFramework.Empty\"\000\022U\n\031SetDriveInterpo"
    "latorOnOff\022\033.Nrmk.IndyFramework.BoolVal\032"
    "\031.Nrmk.IndyFramework.Empty\"\000\022T\n\031SetRotat"
    "ionControllerType\022\032.Nrmk.IndyFramework.I"
    "ntVal\032\031.Nrmk.IndyFramework.Empty\"\000\022[\n\022Se"
    "tForceKinematics\022(.Nrmk.IndyFramework.Fo"
    "rcedKinematicsData\032\031.Nrmk.IndyFramework."
    "Empty\"\000\022[\n\022GetForceKinematics\022\031.Nrmk.Ind"
    "yFramework.Empty\032(.Nrmk.IndyFramework.Fo"
    "rcedKinematicsData\"\000\022G\n\013PauseBumper\022\033.Nr"
    "mk.IndyFramework.BoolVal\032\031.Nrmk.IndyFram"
    "ework.Empty\"\000\022J\n\016TurnLightOnOff\022\033.Nrmk.I"
    "ndyFramework.BoolVal\032\031.Nrmk.IndyFramewor"
    "k.Empty\"\000\022I\n\rTurnBuzzOnOff\022\033.Nrmk.IndyFr"
    "amework.BoolVal\032\031.Nrmk.IndyFramework.Emp"
    "ty\"\000\022G\n\nSetExtraDO\022\034.Nrmk.IndyFramework."
    "BoolVals\032\031.Nrmk.IndyFramework.Empty\"\000\022P\n"
    "\017SetControlParam\022 .Nrmk.IndyFramework.Ro"
    "tationGain\032\031.Nrmk.IndyFramework.Empty\"\000\022"
    "Q\n\017GetControlParam\022\032.Nrmk.IndyFramework."
    "IntVal\032 .Nrmk.IndyFramework.RotationGain"
    "\"\000\022H\n\016StartRTLogging\022\031.Nrmk.IndyFramewor"
    "k.Empty\032\031.Nrmk.IndyFramework.Empty\"\000\022F\n\014"
    "EndRTLogging\022\031.Nrmk.IndyFramework.Empty\032"
    "\031.Nrmk.IndyFramework.Empty\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_moby_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_moby_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_moby_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_moby_2eproto = {
    false,
    false,
    2996,
    descriptor_table_protodef_moby_2eproto,
    "moby.proto",
    &descriptor_table_moby_2eproto_once,
    descriptor_table_moby_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_moby_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_moby_2eproto,
    file_level_service_descriptors_moby_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_moby_2eproto_getter() {
  return &descriptor_table_moby_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_moby_2eproto(&descriptor_table_moby_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
