// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plotting.proto

#include "plotting.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
        template <typename>
PROTOBUF_CONSTEXPR PlottingData::PlottingData(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.q_)*/ {},
      /*decltype(_impl_.qdot_)*/ {},
      /*decltype(_impl_.qddot_)*/ {},
      /*decltype(_impl_.qd_)*/ {},
      /*decltype(_impl_.qdotd_)*/ {},
      /*decltype(_impl_.qddotd_)*/ {},
      /*decltype(_impl_.p_)*/ {},
      /*decltype(_impl_.pdot_)*/ {},
      /*decltype(_impl_.pddot_)*/ {},
      /*decltype(_impl_.pd_)*/ {},
      /*decltype(_impl_.pdotd_)*/ {},
      /*decltype(_impl_.pddotd_)*/ {},
      /*decltype(_impl_.tau_)*/ {},
      /*decltype(_impl_.tauex_)*/ {},
      /*decltype(_impl_.qdotref_)*/ {},
      /*decltype(_impl_.edotref_)*/ {},
      /*decltype(_impl_.tauref_)*/ {},
      /*decltype(_impl_.time_)*/ 0,
      /*decltype(_impl_.op_state_)*/ 0u,
      /*decltype(_impl_.motion_space_)*/ 0u,
      /*decltype(_impl_.traj_state_)*/ 0u,
      /*decltype(_impl_.traj_progress_)*/ 0u,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct PlottingDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlottingDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlottingDataDefaultTypeInternal() {}
  union {
    PlottingData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlottingDataDefaultTypeInternal _PlottingData_default_instance_;
}  // namespace IndyFramework
}  // namespace Nrmk
static ::_pb::Metadata file_level_metadata_plotting_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_plotting_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_plotting_2eproto = nullptr;
const ::uint32_t TableStruct_plotting_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.time_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.op_state_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.motion_space_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.traj_state_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.traj_progress_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.q_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.qdot_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.qddot_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.qd_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.qdotd_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.qddotd_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.p_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.pdot_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.pddot_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.pd_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.pdotd_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.pddotd_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.tau_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.tauex_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.qdotref_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.edotref_),
    PROTOBUF_FIELD_OFFSET(::Nrmk::IndyFramework::PlottingData, _impl_.tauref_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Nrmk::IndyFramework::PlottingData)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Nrmk::IndyFramework::_PlottingData_default_instance_._instance,
};
const char descriptor_table_protodef_plotting_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016plotting.proto\022\022Nrmk.IndyFramework\032\021co"
    "mmon_msgs.proto\"\343\002\n\014PlottingData\022\014\n\004time"
    "\030\001 \001(\001\022\020\n\010op_state\030\002 \001(\r\022\024\n\014motion_space"
    "\030\003 \001(\r\022\022\n\ntraj_state\030\004 \001(\r\022\025\n\rtraj_progr"
    "ess\030\005 \001(\r\022\t\n\001q\030\n \003(\002\022\014\n\004qdot\030\013 \003(\002\022\r\n\005qd"
    "dot\030\014 \003(\002\022\n\n\002qd\030\r \003(\002\022\r\n\005qdotd\030\016 \003(\002\022\016\n\006"
    "qddotd\030\017 \003(\002\022\t\n\001p\030\024 \003(\002\022\014\n\004pdot\030\025 \003(\002\022\r\n"
    "\005pddot\030\026 \003(\002\022\n\n\002pd\030\027 \003(\002\022\r\n\005pdotd\030\030 \003(\002\022"
    "\016\n\006pddotd\030\031 \003(\002\022\013\n\003tau\030\036 \003(\002\022\r\n\005tauex\030\037 "
    "\003(\002\022\017\n\007qdotref\030( \003(\002\022\017\n\007edotref\030) \003(\002\022\016\n"
    "\006tauref\030* \003(\0022g\n\021RTPlottingService\022R\n\017Ge"
    "tPlottingData\022\031.Nrmk.IndyFramework.Empty"
    "\032 .Nrmk.IndyFramework.PlottingData\"\0000\001b\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_plotting_2eproto_deps[1] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_plotting_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_plotting_2eproto = {
    false,
    false,
    526,
    descriptor_table_protodef_plotting_2eproto,
    "plotting.proto",
    &descriptor_table_plotting_2eproto_once,
    descriptor_table_plotting_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_plotting_2eproto::offsets,
    file_level_metadata_plotting_2eproto,
    file_level_enum_descriptors_plotting_2eproto,
    file_level_service_descriptors_plotting_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_plotting_2eproto_getter() {
  return &descriptor_table_plotting_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_plotting_2eproto(&descriptor_table_plotting_2eproto);
namespace Nrmk {
namespace IndyFramework {
// ===================================================================

class PlottingData::_Internal {
 public:
};

PlottingData::PlottingData(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Nrmk.IndyFramework.PlottingData)
}
PlottingData::PlottingData(const PlottingData& from) : ::google::protobuf::Message() {
  PlottingData* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.q_){from._impl_.q_},
      decltype(_impl_.qdot_){from._impl_.qdot_},
      decltype(_impl_.qddot_){from._impl_.qddot_},
      decltype(_impl_.qd_){from._impl_.qd_},
      decltype(_impl_.qdotd_){from._impl_.qdotd_},
      decltype(_impl_.qddotd_){from._impl_.qddotd_},
      decltype(_impl_.p_){from._impl_.p_},
      decltype(_impl_.pdot_){from._impl_.pdot_},
      decltype(_impl_.pddot_){from._impl_.pddot_},
      decltype(_impl_.pd_){from._impl_.pd_},
      decltype(_impl_.pdotd_){from._impl_.pdotd_},
      decltype(_impl_.pddotd_){from._impl_.pddotd_},
      decltype(_impl_.tau_){from._impl_.tau_},
      decltype(_impl_.tauex_){from._impl_.tauex_},
      decltype(_impl_.qdotref_){from._impl_.qdotref_},
      decltype(_impl_.edotref_){from._impl_.edotref_},
      decltype(_impl_.tauref_){from._impl_.tauref_},
      decltype(_impl_.time_){},
      decltype(_impl_.op_state_){},
      decltype(_impl_.motion_space_){},
      decltype(_impl_.traj_state_){},
      decltype(_impl_.traj_progress_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  ::memcpy(&_impl_.time_, &from._impl_.time_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.traj_progress_) -
    reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.traj_progress_));

  // @@protoc_insertion_point(copy_constructor:Nrmk.IndyFramework.PlottingData)
}
inline void PlottingData::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.q_){arena},
      decltype(_impl_.qdot_){arena},
      decltype(_impl_.qddot_){arena},
      decltype(_impl_.qd_){arena},
      decltype(_impl_.qdotd_){arena},
      decltype(_impl_.qddotd_){arena},
      decltype(_impl_.p_){arena},
      decltype(_impl_.pdot_){arena},
      decltype(_impl_.pddot_){arena},
      decltype(_impl_.pd_){arena},
      decltype(_impl_.pdotd_){arena},
      decltype(_impl_.pddotd_){arena},
      decltype(_impl_.tau_){arena},
      decltype(_impl_.tauex_){arena},
      decltype(_impl_.qdotref_){arena},
      decltype(_impl_.edotref_){arena},
      decltype(_impl_.tauref_){arena},
      decltype(_impl_.time_){0},
      decltype(_impl_.op_state_){0u},
      decltype(_impl_.motion_space_){0u},
      decltype(_impl_.traj_state_){0u},
      decltype(_impl_.traj_progress_){0u},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
PlottingData::~PlottingData() {
  // @@protoc_insertion_point(destructor:Nrmk.IndyFramework.PlottingData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PlottingData::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.q_.~RepeatedField();
  _impl_.qdot_.~RepeatedField();
  _impl_.qddot_.~RepeatedField();
  _impl_.qd_.~RepeatedField();
  _impl_.qdotd_.~RepeatedField();
  _impl_.qddotd_.~RepeatedField();
  _impl_.p_.~RepeatedField();
  _impl_.pdot_.~RepeatedField();
  _impl_.pddot_.~RepeatedField();
  _impl_.pd_.~RepeatedField();
  _impl_.pdotd_.~RepeatedField();
  _impl_.pddotd_.~RepeatedField();
  _impl_.tau_.~RepeatedField();
  _impl_.tauex_.~RepeatedField();
  _impl_.qdotref_.~RepeatedField();
  _impl_.edotref_.~RepeatedField();
  _impl_.tauref_.~RepeatedField();
}
void PlottingData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void PlottingData::Clear() {
// @@protoc_insertion_point(message_clear_start:Nrmk.IndyFramework.PlottingData)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_q()->Clear();
  _internal_mutable_qdot()->Clear();
  _internal_mutable_qddot()->Clear();
  _internal_mutable_qd()->Clear();
  _internal_mutable_qdotd()->Clear();
  _internal_mutable_qddotd()->Clear();
  _internal_mutable_p()->Clear();
  _internal_mutable_pdot()->Clear();
  _internal_mutable_pddot()->Clear();
  _internal_mutable_pd()->Clear();
  _internal_mutable_pdotd()->Clear();
  _internal_mutable_pddotd()->Clear();
  _internal_mutable_tau()->Clear();
  _internal_mutable_tauex()->Clear();
  _internal_mutable_qdotref()->Clear();
  _internal_mutable_edotref()->Clear();
  _internal_mutable_tauref()->Clear();
  ::memset(&_impl_.time_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.traj_progress_) -
      reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.traj_progress_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PlottingData::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 22, 0, 0, 7> PlottingData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    42, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    2651292128,  // skipmap
    offsetof(decltype(_table_), field_entries),
    22,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PlottingData_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double time = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.time_)}},
    // uint32 op_state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlottingData, _impl_.op_state_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.op_state_)}},
    // uint32 motion_space = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlottingData, _impl_.motion_space_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.motion_space_)}},
    // uint32 traj_state = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlottingData, _impl_.traj_state_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.traj_state_)}},
    // uint32 traj_progress = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlottingData, _impl_.traj_progress_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.traj_progress_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float q = 10;
    {::_pbi::TcParser::FastF32P1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.q_)}},
    // repeated float qdot = 11;
    {::_pbi::TcParser::FastF32P1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qdot_)}},
    // repeated float qddot = 12;
    {::_pbi::TcParser::FastF32P1,
     {98, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qddot_)}},
    // repeated float qd = 13;
    {::_pbi::TcParser::FastF32P1,
     {106, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qd_)}},
    // repeated float qdotd = 14;
    {::_pbi::TcParser::FastF32P1,
     {114, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qdotd_)}},
    // repeated float qddotd = 15;
    {::_pbi::TcParser::FastF32P1,
     {122, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qddotd_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float p = 20;
    {::_pbi::TcParser::FastF32P2,
     {418, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.p_)}},
    // repeated float pdot = 21;
    {::_pbi::TcParser::FastF32P2,
     {426, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pdot_)}},
    // repeated float pddot = 22;
    {::_pbi::TcParser::FastF32P2,
     {434, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pddot_)}},
    // repeated float pd = 23;
    {::_pbi::TcParser::FastF32P2,
     {442, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pd_)}},
    // repeated float pdotd = 24;
    {::_pbi::TcParser::FastF32P2,
     {450, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pdotd_)}},
    // repeated float pddotd = 25;
    {::_pbi::TcParser::FastF32P2,
     {458, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pddotd_)}},
    // repeated float tauref = 42;
    {::_pbi::TcParser::FastF32P2,
     {722, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.tauref_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float tau = 30;
    {::_pbi::TcParser::FastF32P2,
     {498, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.tau_)}},
    // repeated float tauex = 31;
    {::_pbi::TcParser::FastF32P2,
     {506, 63, 0, PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.tauex_)}},
  }}, {{
    40, 0, 1,
    65528, 19,
    65535, 65535
  }}, {{
    // double time = 1;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // uint32 op_state = 2;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.op_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 motion_space = 3;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.motion_space_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 traj_state = 4;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.traj_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 traj_progress = 5;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.traj_progress_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated float q = 10;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.q_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float qdot = 11;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qdot_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float qddot = 12;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qddot_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float qd = 13;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qd_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float qdotd = 14;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qdotd_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float qddotd = 15;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qddotd_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float p = 20;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.p_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float pdot = 21;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pdot_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float pddot = 22;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pddot_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float pd = 23;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pd_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float pdotd = 24;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pdotd_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float pddotd = 25;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.pddotd_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tau = 30;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.tau_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tauex = 31;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.tauex_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float qdotref = 40;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.qdotref_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float edotref = 41;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.edotref_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tauref = 42;
    {PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.tauref_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* PlottingData::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Nrmk.IndyFramework.PlottingData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double time = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_time(), target);
  }

  // uint32 op_state = 2;
  if (this->_internal_op_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_op_state(), target);
  }

  // uint32 motion_space = 3;
  if (this->_internal_motion_space() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_motion_space(), target);
  }

  // uint32 traj_state = 4;
  if (this->_internal_traj_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_traj_state(), target);
  }

  // uint32 traj_progress = 5;
  if (this->_internal_traj_progress() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_traj_progress(), target);
  }

  // repeated float q = 10;
  if (this->_internal_q_size() > 0) {
    target = stream->WriteFixedPacked(10, _internal_q(), target);
  }

  // repeated float qdot = 11;
  if (this->_internal_qdot_size() > 0) {
    target = stream->WriteFixedPacked(11, _internal_qdot(), target);
  }

  // repeated float qddot = 12;
  if (this->_internal_qddot_size() > 0) {
    target = stream->WriteFixedPacked(12, _internal_qddot(), target);
  }

  // repeated float qd = 13;
  if (this->_internal_qd_size() > 0) {
    target = stream->WriteFixedPacked(13, _internal_qd(), target);
  }

  // repeated float qdotd = 14;
  if (this->_internal_qdotd_size() > 0) {
    target = stream->WriteFixedPacked(14, _internal_qdotd(), target);
  }

  // repeated float qddotd = 15;
  if (this->_internal_qddotd_size() > 0) {
    target = stream->WriteFixedPacked(15, _internal_qddotd(), target);
  }

  // repeated float p = 20;
  if (this->_internal_p_size() > 0) {
    target = stream->WriteFixedPacked(20, _internal_p(), target);
  }

  // repeated float pdot = 21;
  if (this->_internal_pdot_size() > 0) {
    target = stream->WriteFixedPacked(21, _internal_pdot(), target);
  }

  // repeated float pddot = 22;
  if (this->_internal_pddot_size() > 0) {
    target = stream->WriteFixedPacked(22, _internal_pddot(), target);
  }

  // repeated float pd = 23;
  if (this->_internal_pd_size() > 0) {
    target = stream->WriteFixedPacked(23, _internal_pd(), target);
  }

  // repeated float pdotd = 24;
  if (this->_internal_pdotd_size() > 0) {
    target = stream->WriteFixedPacked(24, _internal_pdotd(), target);
  }

  // repeated float pddotd = 25;
  if (this->_internal_pddotd_size() > 0) {
    target = stream->WriteFixedPacked(25, _internal_pddotd(), target);
  }

  // repeated float tau = 30;
  if (this->_internal_tau_size() > 0) {
    target = stream->WriteFixedPacked(30, _internal_tau(), target);
  }

  // repeated float tauex = 31;
  if (this->_internal_tauex_size() > 0) {
    target = stream->WriteFixedPacked(31, _internal_tauex(), target);
  }

  // repeated float qdotref = 40;
  if (this->_internal_qdotref_size() > 0) {
    target = stream->WriteFixedPacked(40, _internal_qdotref(), target);
  }

  // repeated float edotref = 41;
  if (this->_internal_edotref_size() > 0) {
    target = stream->WriteFixedPacked(41, _internal_edotref(), target);
  }

  // repeated float tauref = 42;
  if (this->_internal_tauref_size() > 0) {
    target = stream->WriteFixedPacked(42, _internal_tauref(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Nrmk.IndyFramework.PlottingData)
  return target;
}

::size_t PlottingData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Nrmk.IndyFramework.PlottingData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float q = 10;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_q_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float qdot = 11;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_qdot_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float qddot = 12;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_qddot_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float qd = 13;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_qd_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float qdotd = 14;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_qdotd_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float qddotd = 15;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_qddotd_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float p = 20;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_p_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float pdot = 21;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_pdot_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float pddot = 22;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_pddot_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float pd = 23;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_pd_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float pdotd = 24;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_pdotd_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float pddotd = 25;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_pddotd_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tau = 30;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tau_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tauex = 31;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tauex_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float qdotref = 40;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_qdotref_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float edotref = 41;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_edotref_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tauref = 42;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tauref_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // double time = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    total_size += 9;
  }

  // uint32 op_state = 2;
  if (this->_internal_op_state() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_op_state());
  }

  // uint32 motion_space = 3;
  if (this->_internal_motion_space() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_motion_space());
  }

  // uint32 traj_state = 4;
  if (this->_internal_traj_state() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_traj_state());
  }

  // uint32 traj_progress = 5;
  if (this->_internal_traj_progress() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_traj_progress());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PlottingData::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    PlottingData::MergeImpl
};
const ::google::protobuf::Message::ClassData*PlottingData::GetClassData() const { return &_class_data_; }


void PlottingData::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PlottingData*>(&to_msg);
  auto& from = static_cast<const PlottingData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Nrmk.IndyFramework.PlottingData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_q()->MergeFrom(from._internal_q());
  _this->_internal_mutable_qdot()->MergeFrom(from._internal_qdot());
  _this->_internal_mutable_qddot()->MergeFrom(from._internal_qddot());
  _this->_internal_mutable_qd()->MergeFrom(from._internal_qd());
  _this->_internal_mutable_qdotd()->MergeFrom(from._internal_qdotd());
  _this->_internal_mutable_qddotd()->MergeFrom(from._internal_qddotd());
  _this->_internal_mutable_p()->MergeFrom(from._internal_p());
  _this->_internal_mutable_pdot()->MergeFrom(from._internal_pdot());
  _this->_internal_mutable_pddot()->MergeFrom(from._internal_pddot());
  _this->_internal_mutable_pd()->MergeFrom(from._internal_pd());
  _this->_internal_mutable_pdotd()->MergeFrom(from._internal_pdotd());
  _this->_internal_mutable_pddotd()->MergeFrom(from._internal_pddotd());
  _this->_internal_mutable_tau()->MergeFrom(from._internal_tau());
  _this->_internal_mutable_tauex()->MergeFrom(from._internal_tauex());
  _this->_internal_mutable_qdotref()->MergeFrom(from._internal_qdotref());
  _this->_internal_mutable_edotref()->MergeFrom(from._internal_edotref());
  _this->_internal_mutable_tauref()->MergeFrom(from._internal_tauref());
  static_assert(sizeof(::uint64_t) == sizeof(double),
                "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = from._internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  if (from._internal_op_state() != 0) {
    _this->_internal_set_op_state(from._internal_op_state());
  }
  if (from._internal_motion_space() != 0) {
    _this->_internal_set_motion_space(from._internal_motion_space());
  }
  if (from._internal_traj_state() != 0) {
    _this->_internal_set_traj_state(from._internal_traj_state());
  }
  if (from._internal_traj_progress() != 0) {
    _this->_internal_set_traj_progress(from._internal_traj_progress());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PlottingData::CopyFrom(const PlottingData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Nrmk.IndyFramework.PlottingData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PlottingData::IsInitialized() const {
  return true;
}

void PlottingData::InternalSwap(PlottingData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.q_.InternalSwap(&other->_impl_.q_);
  _impl_.qdot_.InternalSwap(&other->_impl_.qdot_);
  _impl_.qddot_.InternalSwap(&other->_impl_.qddot_);
  _impl_.qd_.InternalSwap(&other->_impl_.qd_);
  _impl_.qdotd_.InternalSwap(&other->_impl_.qdotd_);
  _impl_.qddotd_.InternalSwap(&other->_impl_.qddotd_);
  _impl_.p_.InternalSwap(&other->_impl_.p_);
  _impl_.pdot_.InternalSwap(&other->_impl_.pdot_);
  _impl_.pddot_.InternalSwap(&other->_impl_.pddot_);
  _impl_.pd_.InternalSwap(&other->_impl_.pd_);
  _impl_.pdotd_.InternalSwap(&other->_impl_.pdotd_);
  _impl_.pddotd_.InternalSwap(&other->_impl_.pddotd_);
  _impl_.tau_.InternalSwap(&other->_impl_.tau_);
  _impl_.tauex_.InternalSwap(&other->_impl_.tauex_);
  _impl_.qdotref_.InternalSwap(&other->_impl_.qdotref_);
  _impl_.edotref_.InternalSwap(&other->_impl_.edotref_);
  _impl_.tauref_.InternalSwap(&other->_impl_.tauref_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.traj_progress_)
      + sizeof(PlottingData::_impl_.traj_progress_)
      - PROTOBUF_FIELD_OFFSET(PlottingData, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::google::protobuf::Metadata PlottingData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_plotting_2eproto_getter, &descriptor_table_plotting_2eproto_once,
      file_level_metadata_plotting_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
