// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: teleop_dev.proto

#include "teleop_dev.pb.h"
#include "teleop_dev.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace IndyFramework {
namespace Protobuf {
namespace TeleDev {

static const char* TeleOpDevice_method_names[] = {
  "/IndyFramework.Protobuf.TeleDev.TeleOpDevice/StartTeleOpStream",
  "/IndyFramework.Protobuf.TeleDev.TeleOpDevice/StopTeleOpStream",
};

std::unique_ptr< TeleOpDevice::Stub> TeleOpDevice::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TeleOpDevice::Stub> stub(new TeleOpDevice::Stub(channel, options));
  return stub;
}

TeleOpDevice::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StartTeleOpStream_(TeleOpDevice_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopTeleOpStream_(TeleOpDevice_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TeleOpDevice::Stub::StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::IndyFramework::Protobuf::TeleDev::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartTeleOpStream_, context, request, response);
}

void TeleOpDevice::Stub::async::StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartTeleOpStream_, context, request, response, std::move(f));
}

void TeleOpDevice::Stub::async::StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartTeleOpStream_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* TeleOpDevice::Stub::PrepareAsyncStartTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IndyFramework::Protobuf::TeleDev::Response, ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartTeleOpStream_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* TeleOpDevice::Stub::AsyncStartTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartTeleOpStreamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOpDevice::Stub::StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::IndyFramework::Protobuf::TeleDev::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopTeleOpStream_, context, request, response);
}

void TeleOpDevice::Stub::async::StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopTeleOpStream_, context, request, response, std::move(f));
}

void TeleOpDevice::Stub::async::StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopTeleOpStream_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* TeleOpDevice::Stub::PrepareAsyncStopTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IndyFramework::Protobuf::TeleDev::Response, ::IndyFramework::Protobuf::TeleDev::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopTeleOpStream_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* TeleOpDevice::Stub::AsyncStopTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopTeleOpStreamRaw(context, request, cq);
  result->StartCall();
  return result;
}

TeleOpDevice::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOpDevice_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOpDevice::Service, ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOpDevice::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* req,
             ::IndyFramework::Protobuf::TeleDev::Response* resp) {
               return service->StartTeleOpStream(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOpDevice_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOpDevice::Service, ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOpDevice::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IndyFramework::Protobuf::TeleDev::Empty* req,
             ::IndyFramework::Protobuf::TeleDev::Response* resp) {
               return service->StopTeleOpStream(ctx, req, resp);
             }, this)));
}

TeleOpDevice::Service::~Service() {
}

::grpc::Status TeleOpDevice::Service::StartTeleOpStream(::grpc::ServerContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOpDevice::Service::StopTeleOpStream(::grpc::ServerContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace IndyFramework
}  // namespace Protobuf
}  // namespace TeleDev

