// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: teleop_dev.proto
#ifndef GRPC_teleop_5fdev_2eproto__INCLUDED
#define GRPC_teleop_5fdev_2eproto__INCLUDED

#include "teleop_dev.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace IndyFramework {
namespace Protobuf {
namespace TeleDev {

class TeleOpDevice final {
 public:
  static constexpr char const* service_full_name() {
    return "IndyFramework.Protobuf.TeleDev.TeleOpDevice";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::IndyFramework::Protobuf::TeleDev::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>> AsyncStartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>>(AsyncStartTeleOpStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>> PrepareAsyncStartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>>(PrepareAsyncStartTeleOpStreamRaw(context, request, cq));
    }
    virtual ::grpc::Status StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::IndyFramework::Protobuf::TeleDev::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>> AsyncStopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>>(AsyncStopTeleOpStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>> PrepareAsyncStopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>>(PrepareAsyncStopTeleOpStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>* AsyncStartTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>* PrepareAsyncStartTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>* AsyncStopTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IndyFramework::Protobuf::TeleDev::Response>* PrepareAsyncStopTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::IndyFramework::Protobuf::TeleDev::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>> AsyncStartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>>(AsyncStartTeleOpStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>> PrepareAsyncStartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>>(PrepareAsyncStartTeleOpStreamRaw(context, request, cq));
    }
    ::grpc::Status StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::IndyFramework::Protobuf::TeleDev::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>> AsyncStopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>>(AsyncStopTeleOpStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>> PrepareAsyncStopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>>(PrepareAsyncStopTeleOpStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response, std::function<void(::grpc::Status)>) override;
      void StartTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response, std::function<void(::grpc::Status)>) override;
      void StopTeleOpStream(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* AsyncStartTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* PrepareAsyncStartTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* AsyncStopTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::IndyFramework::Protobuf::TeleDev::Response>* PrepareAsyncStopTeleOpStreamRaw(::grpc::ClientContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartTeleOpStream_;
    const ::grpc::internal::RpcMethod rpcmethod_StopTeleOpStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StartTeleOpStream(::grpc::ServerContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response);
    virtual ::grpc::Status StopTeleOpStream(::grpc::ServerContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartTeleOpStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTeleOpStream(::grpc::ServerContext* context, ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::grpc::ServerAsyncResponseWriter< ::IndyFramework::Protobuf::TeleDev::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StopTeleOpStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StopTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopTeleOpStream(::grpc::ServerContext* context, ::IndyFramework::Protobuf::TeleDev::Empty* request, ::grpc::ServerAsyncResponseWriter< ::IndyFramework::Protobuf::TeleDev::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartTeleOpStream<WithAsyncMethod_StopTeleOpStream<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StartTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartTeleOpStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* request, ::IndyFramework::Protobuf::TeleDev::Response* response) { return this->StartTeleOpStream(context, request, response); }));}
    void SetMessageAllocatorFor_StartTeleOpStream(
        ::grpc::MessageAllocator< ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartTeleOpStream(
      ::grpc::CallbackServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StopTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StopTeleOpStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::IndyFramework::Protobuf::TeleDev::Empty* request, ::IndyFramework::Protobuf::TeleDev::Response* response) { return this->StopTeleOpStream(context, request, response); }));}
    void SetMessageAllocatorFor_StopTeleOpStream(
        ::grpc::MessageAllocator< ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StopTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopTeleOpStream(
      ::grpc::CallbackServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StartTeleOpStream<WithCallbackMethod_StopTeleOpStream<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartTeleOpStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StopTeleOpStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StopTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartTeleOpStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartTeleOpStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StopTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StopTeleOpStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StopTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopTeleOpStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartTeleOpStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartTeleOpStream(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartTeleOpStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StopTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StopTeleOpStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StopTeleOpStream(context, request, response); }));
    }
    ~WithRawCallbackMethod_StopTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopTeleOpStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartTeleOpStream() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq, ::IndyFramework::Protobuf::TeleDev::Response>* streamer) {
                       return this->StreamedStartTeleOpStream(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartTeleOpStream(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::IndyFramework::Protobuf::TeleDev::TeleOpStreamReq,::IndyFramework::Protobuf::TeleDev::Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StopTeleOpStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StopTeleOpStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::IndyFramework::Protobuf::TeleDev::Empty, ::IndyFramework::Protobuf::TeleDev::Response>* streamer) {
                       return this->StreamedStopTeleOpStream(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StopTeleOpStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StopTeleOpStream(::grpc::ServerContext* /*context*/, const ::IndyFramework::Protobuf::TeleDev::Empty* /*request*/, ::IndyFramework::Protobuf::TeleDev::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStopTeleOpStream(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::IndyFramework::Protobuf::TeleDev::Empty,::IndyFramework::Protobuf::TeleDev::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartTeleOpStream<WithStreamedUnaryMethod_StopTeleOpStream<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartTeleOpStream<WithStreamedUnaryMethod_StopTeleOpStream<Service > > StreamedService;
};

}  // namespace TeleDev
}  // namespace Protobuf
}  // namespace IndyFramework


#endif  // GRPC_teleop_5fdev_2eproto__INCLUDED
